/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 logoPP1.glb -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/../logoPP1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Text" geometry={nodes.Text.geometry} material={nodes.Text.material} position={[1.269, 0.018, -0.237]} rotation={[1.57, 0, 0]} />
      <mesh name="Text001" geometry={nodes.Text001.geometry} material={nodes.Text001.material} position={[-1.275, 0.013, -0.236]} rotation={[1.572, 0, -Math.PI]} />
      <group name="Text_cell" position={[1.758, 0.225, -0.331]}>
        <mesh name="Text_cell080_1" geometry={nodes.Text_cell080_1.geometry} material={nodes.Text_cell080_1.material} />
        <mesh name="Text_cell080_2" geometry={nodes.Text_cell080_2.geometry} material={nodes.Text_cell080_2.material} />
      </group>
      <group name="Text_cell001" position={[0.671, 1.278, -0.326]}>
        <mesh name="Text_cell081" geometry={nodes.Text_cell081.geometry} material={nodes.Text_cell081.material} />
        <mesh name="Text_cell081_1" geometry={nodes.Text_cell081_1.geometry} material={nodes.Text_cell081_1.material} />
      </group>
      <group name="Text_cell002" position={[1.812, 1.473, -0.316]}>
        <mesh name="Text_cell001_1" geometry={nodes.Text_cell001_1.geometry} material={nodes.Text_cell001_1.material} />
        <mesh name="Text_cell001_2" geometry={nodes.Text_cell001_2.geometry} material={nodes.Text_cell001_2.material} />
      </group>
      <group name="Text_cell003" position={[1.475, -0.08, -0.148]}>
        <mesh name="Text_cell002_1" geometry={nodes.Text_cell002_1.geometry} material={nodes.Text_cell002_1.material} />
        <mesh name="Text_cell002_2" geometry={nodes.Text_cell002_2.geometry} material={nodes.Text_cell002_2.material} />
      </group>
      <group name="Text_cell004" position={[0.349, -1.113, -0.343]}>
        <mesh name="Text_cell003_1" geometry={nodes.Text_cell003_1.geometry} material={nodes.Text_cell003_1.material} />
        <mesh name="Text_cell003_2" geometry={nodes.Text_cell003_2.geometry} material={nodes.Text_cell003_2.material} />
      </group>
      <group name="Text_cell005" position={[1.421, 1.6, -0.127]}>
        <mesh name="Text_cell004_1" geometry={nodes.Text_cell004_1.geometry} material={nodes.Text_cell004_1.material} />
        <mesh name="Text_cell004_2" geometry={nodes.Text_cell004_2.geometry} material={nodes.Text_cell004_2.material} />
      </group>
      <group name="Text_cell006" position={[1.962, 0.822, -0.359]}>
        <mesh name="Text_cell005_1" geometry={nodes.Text_cell005_1.geometry} material={nodes.Text_cell005_1.material} />
        <mesh name="Text_cell005_2" geometry={nodes.Text_cell005_2.geometry} material={nodes.Text_cell005_2.material} />
      </group>
      <group name="Text_cell007" position={[0.582, 0.017, -0.144]}>
        <mesh name="Text_cell006_1" geometry={nodes.Text_cell006_1.geometry} material={nodes.Text_cell006_1.material} />
        <mesh name="Text_cell006_2" geometry={nodes.Text_cell006_2.geometry} material={nodes.Text_cell006_2.material} />
      </group>
      <group name="Text_cell008" position={[1.962, 0.694, -0.333]}>
        <mesh name="Text_cell007_1" geometry={nodes.Text_cell007_1.geometry} material={nodes.Text_cell007_1.material} />
        <mesh name="Text_cell007_2" geometry={nodes.Text_cell007_2.geometry} material={nodes.Text_cell007_2.material} />
      </group>
      <group name="Text_cell009" position={[1.79, 0.03, -0.175]}>
        <mesh name="Text_cell008_1" geometry={nodes.Text_cell008_1.geometry} material={nodes.Text_cell008_1.material} />
        <mesh name="Text_cell008_2" geometry={nodes.Text_cell008_2.geometry} material={nodes.Text_cell008_2.material} />
      </group>
      <group name="Text_cell010" position={[1.656, -0.027, -0.13]}>
        <mesh name="Text_cell009_1" geometry={nodes.Text_cell009_1.geometry} material={nodes.Text_cell009_1.material} />
        <mesh name="Text_cell009_2" geometry={nodes.Text_cell009_2.geometry} material={nodes.Text_cell009_2.material} />
      </group>
      <group name="Text_cell011" position={[2.191, 0.475, -0.146]}>
        <mesh name="Text_cell010_1" geometry={nodes.Text_cell010_1.geometry} material={nodes.Text_cell010_1.material} />
        <mesh name="Text_cell010_2" geometry={nodes.Text_cell010_2.geometry} material={nodes.Text_cell010_2.material} />
      </group>
      <group name="Text_cell012" position={[1.922, 0.619, -0.13]}>
        <mesh name="Text_cell011_1" geometry={nodes.Text_cell011_1.geometry} material={nodes.Text_cell011_1.material} />
        <mesh name="Text_cell011_2" geometry={nodes.Text_cell011_2.geometry} material={nodes.Text_cell011_2.material} />
      </group>
      <group name="Text_cell013" position={[1.519, 0.173, -0.12]}>
        <mesh name="Text_cell012_1" geometry={nodes.Text_cell012_1.geometry} material={nodes.Text_cell012_1.material} />
        <mesh name="Text_cell012_2" geometry={nodes.Text_cell012_2.geometry} material={nodes.Text_cell012_2.material} />
      </group>
      <group name="Text_cell014" position={[1.955, 0.807, -0.137]}>
        <mesh name="Text_cell013_1" geometry={nodes.Text_cell013_1.geometry} material={nodes.Text_cell013_1.material} />
        <mesh name="Text_cell013_2" geometry={nodes.Text_cell013_2.geometry} material={nodes.Text_cell013_2.material} />
      </group>
      <group name="Text_cell015" position={[2.185, 0.998, -0.146]}>
        <mesh name="Text_cell014_1" geometry={nodes.Text_cell014_1.geometry} material={nodes.Text_cell014_1.material} />
        <mesh name="Text_cell014_2" geometry={nodes.Text_cell014_2.geometry} material={nodes.Text_cell014_2.material} />
      </group>
      <group name="Text_cell016" position={[1.577, 1.569, -0.171]}>
        <mesh name="Text_cell015_1" geometry={nodes.Text_cell015_1.geometry} material={nodes.Text_cell015_1.material} />
        <mesh name="Text_cell015_2" geometry={nodes.Text_cell015_2.geometry} material={nodes.Text_cell015_2.material} />
      </group>
      <group name="Text_cell017" position={[1.226, 0.131, -0.149]}>
        <mesh name="Text_cell016_1" geometry={nodes.Text_cell016_1.geometry} material={nodes.Text_cell016_1.material} />
        <mesh name="Text_cell016_2" geometry={nodes.Text_cell016_2.geometry} material={nodes.Text_cell016_2.material} />
      </group>
      <group name="Text_cell018" position={[2.063, 1.269, -0.358]}>
        <mesh name="Text_cell017_1" geometry={nodes.Text_cell017_1.geometry} material={nodes.Text_cell017_1.material} />
        <mesh name="Text_cell017_2" geometry={nodes.Text_cell017_2.geometry} material={nodes.Text_cell017_2.material} />
      </group>
      <group name="Text_cell019" position={[1.664, 1.31, -0.163]}>
        <mesh name="Text_cell018_1" geometry={nodes.Text_cell018_1.geometry} material={nodes.Text_cell018_1.material} />
        <mesh name="Text_cell018_2" geometry={nodes.Text_cell018_2.geometry} material={nodes.Text_cell018_2.material} />
      </group>
      <group name="Text_cell020" position={[1.735, 1.264, -0.159]}>
        <mesh name="Text_cell019_1" geometry={nodes.Text_cell019_1.geometry} material={nodes.Text_cell019_1.material} />
        <mesh name="Text_cell019_2" geometry={nodes.Text_cell019_2.geometry} material={nodes.Text_cell019_2.material} />
      </group>
      <group name="Text_cell021" position={[1.381, 1.354, -0.344]}>
        <mesh name="Text_cell020_1" geometry={nodes.Text_cell020_1.geometry} material={nodes.Text_cell020_1.material} />
        <mesh name="Text_cell020_2" geometry={nodes.Text_cell020_2.geometry} material={nodes.Text_cell020_2.material} />
      </group>
      <group name="Text_cell022" position={[0.569, -1.204, -0.111]}>
        <mesh name="Text_cell021_1" geometry={nodes.Text_cell021_1.geometry} material={nodes.Text_cell021_1.material} />
        <mesh name="Text_cell021_2" geometry={nodes.Text_cell021_2.geometry} material={nodes.Text_cell021_2.material} />
      </group>
      <group name="Text_cell023" position={[2.2, 0.982, -0.337]}>
        <mesh name="Text_cell022_1" geometry={nodes.Text_cell022_1.geometry} material={nodes.Text_cell022_1.material} />
        <mesh name="Text_cell022_2" geometry={nodes.Text_cell022_2.geometry} material={nodes.Text_cell022_2.material} />
      </group>
      <group name="Text_cell024" position={[1.724, 1.533, -0.15]}>
        <mesh name="Text_cell023_1" geometry={nodes.Text_cell023_1.geometry} material={nodes.Text_cell023_1.material} />
        <mesh name="Text_cell023_2" geometry={nodes.Text_cell023_2.geometry} material={nodes.Text_cell023_2.material} />
      </group>
      <group name="Text_cell025" position={[2.153, 1.196, -0.344]}>
        <mesh name="Text_cell024_1" geometry={nodes.Text_cell024_1.geometry} material={nodes.Text_cell024_1.material} />
        <mesh name="Text_cell024_2" geometry={nodes.Text_cell024_2.geometry} material={nodes.Text_cell024_2.material} />
      </group>
      <group name="Text_cell026" position={[1.782, 1.223, -0.334]}>
        <mesh name="Text_cell025_1" geometry={nodes.Text_cell025_1.geometry} material={nodes.Text_cell025_1.material} />
        <mesh name="Text_cell025_2" geometry={nodes.Text_cell025_2.geometry} material={nodes.Text_cell025_2.material} />
      </group>
      <group name="Text_cell027" position={[1.94, 0.962, -0.361]}>
        <mesh name="Text_cell026_1" geometry={nodes.Text_cell026_1.geometry} material={nodes.Text_cell026_1.material} />
        <mesh name="Text_cell026_2" geometry={nodes.Text_cell026_2.geometry} material={nodes.Text_cell026_2.material} />
      </group>
      <group name="Text_cell028" position={[1.863, 0.365, -0.134]}>
        <mesh name="Text_cell027_1" geometry={nodes.Text_cell027_1.geometry} material={nodes.Text_cell027_1.material} />
        <mesh name="Text_cell027_2" geometry={nodes.Text_cell027_2.geometry} material={nodes.Text_cell027_2.material} />
      </group>
      <group name="Text_cell029" position={[2.23, 0.868, -0.138]}>
        <mesh name="Text_cell028_1" geometry={nodes.Text_cell028_1.geometry} material={nodes.Text_cell028_1.material} />
        <mesh name="Text_cell028_2" geometry={nodes.Text_cell028_2.geometry} material={nodes.Text_cell028_2.material} />
      </group>
      <group name="Text_cell030" position={[2.009, 1.358, -0.339]}>
        <mesh name="Text_cell029_1" geometry={nodes.Text_cell029_1.geometry} material={nodes.Text_cell029_1.material} />
        <mesh name="Text_cell029_2" geometry={nodes.Text_cell029_2.geometry} material={nodes.Text_cell029_2.material} />
      </group>
      <group name="Text_cell031" position={[2.057, 0.23, -0.333]}>
        <mesh name="Text_cell030_1" geometry={nodes.Text_cell030_1.geometry} material={nodes.Text_cell030_1.material} />
        <mesh name="Text_cell030_2" geometry={nodes.Text_cell030_2.geometry} material={nodes.Text_cell030_2.material} />
      </group>
      <group name="Text_cell032" position={[1.944, 0.984, -0.132]}>
        <mesh name="Text_cell031_1" geometry={nodes.Text_cell031_1.geometry} material={nodes.Text_cell031_1.material} />
        <mesh name="Text_cell031_2" geometry={nodes.Text_cell031_2.geometry} material={nodes.Text_cell031_2.material} />
      </group>
      <group name="Text_cell033" position={[1.712, 0.253, -0.131]}>
        <mesh name="Text_cell032_1" geometry={nodes.Text_cell032_1.geometry} material={nodes.Text_cell032_1.material} />
        <mesh name="Text_cell032_2" geometry={nodes.Text_cell032_2.geometry} material={nodes.Text_cell032_2.material} />
      </group>
      <group name="Text_cell034" position={[2.048, 0.203, -0.161]}>
        <mesh name="Text_cell033_1" geometry={nodes.Text_cell033_1.geometry} material={nodes.Text_cell033_1.material} />
        <mesh name="Text_cell033_2" geometry={nodes.Text_cell033_2.geometry} material={nodes.Text_cell033_2.material} />
      </group>
      <group name="Text_cell035" position={[1.92, 0.1, -0.132]}>
        <mesh name="Text_cell034_1" geometry={nodes.Text_cell034_1.geometry} material={nodes.Text_cell034_1.material} />
        <mesh name="Text_cell034_2" geometry={nodes.Text_cell034_2.geometry} material={nodes.Text_cell034_2.material} />
      </group>
      <group name="Text_cell036" position={[1.689, -0.019, -0.344]}>
        <mesh name="Text_cell035_1" geometry={nodes.Text_cell035_1.geometry} material={nodes.Text_cell035_1.material} />
        <mesh name="Text_cell035_2" geometry={nodes.Text_cell035_2.geometry} material={nodes.Text_cell035_2.material} />
      </group>
      <group name="Text_cell037" position={[1.878, 1.065, -0.348]}>
        <mesh name="Text_cell036_1" geometry={nodes.Text_cell036_1.geometry} material={nodes.Text_cell036_1.material} />
        <mesh name="Text_cell036_2" geometry={nodes.Text_cell036_2.geometry} material={nodes.Text_cell036_2.material} />
      </group>
      <group name="Text_cell038" position={[1.887, 1.074, -0.13]}>
        <mesh name="Text_cell037_1" geometry={nodes.Text_cell037_1.geometry} material={nodes.Text_cell037_1.material} />
        <mesh name="Text_cell037_2" geometry={nodes.Text_cell037_2.geometry} material={nodes.Text_cell037_2.material} />
      </group>
      <group name="Text_cell039" position={[2.007, 1.371, -0.138]}>
        <mesh name="Text_cell038_1" geometry={nodes.Text_cell038_1.geometry} material={nodes.Text_cell038_1.material} />
        <mesh name="Text_cell038_2" geometry={nodes.Text_cell038_2.geometry} material={nodes.Text_cell038_2.material} />
      </group>
      <group name="Text_cell040" position={[1.93, 0.572, -0.354]}>
        <mesh name="Text_cell039_1" geometry={nodes.Text_cell039_1.geometry} material={nodes.Text_cell039_1.material} />
        <mesh name="Text_cell039_2" geometry={nodes.Text_cell039_2.geometry} material={nodes.Text_cell039_2.material} />
      </group>
      <group name="Text_cell041" position={[2.167, 1.085, -0.334]}>
        <mesh name="Text_cell040_1" geometry={nodes.Text_cell040_1.geometry} material={nodes.Text_cell040_1.material} />
        <mesh name="Text_cell040_2" geometry={nodes.Text_cell040_2.geometry} material={nodes.Text_cell040_2.material} />
      </group>
      <group name="Text_cell042" position={[2.127, 0.329, -0.144]}>
        <mesh name="Text_cell041_1" geometry={nodes.Text_cell041_1.geometry} material={nodes.Text_cell041_1.material} />
        <mesh name="Text_cell041_2" geometry={nodes.Text_cell041_2.geometry} material={nodes.Text_cell041_2.material} />
      </group>
      <group name="Text_cell043" position={[1.153, 1.597, -0.339]}>
        <mesh name="Text_cell042_1" geometry={nodes.Text_cell042_1.geometry} material={nodes.Text_cell042_1.material} />
        <mesh name="Text_cell042_2" geometry={nodes.Text_cell042_2.geometry} material={nodes.Text_cell042_2.material} />
      </group>
      <group name="Text_cell044" position={[2.221, 0.858, -0.347]}>
        <mesh name="Text_cell043_1" geometry={nodes.Text_cell043_1.geometry} material={nodes.Text_cell043_1.material} />
        <mesh name="Text_cell043_2" geometry={nodes.Text_cell043_2.geometry} material={nodes.Text_cell043_2.material} />
      </group>
      <group name="Text_cell045" position={[0.354, 1.527, -0.342]}>
        <mesh name="Text_cell044_1" geometry={nodes.Text_cell044_1.geometry} material={nodes.Text_cell044_1.material} />
        <mesh name="Text_cell044_2" geometry={nodes.Text_cell044_2.geometry} material={nodes.Text_cell044_2.material} />
      </group>
      <group name="Text_cell046" position={[2.14, 1.149, -0.134]}>
        <mesh name="Text_cell045_1" geometry={nodes.Text_cell045_1.geometry} material={nodes.Text_cell045_1.material} />
        <mesh name="Text_cell045_2" geometry={nodes.Text_cell045_2.geometry} material={nodes.Text_cell045_2.material} />
      </group>
      <group name="Text_cell047" position={[1.091, -0.105, -0.206]}>
        <mesh name="Text_cell046_1" geometry={nodes.Text_cell046_1.geometry} material={nodes.Text_cell046_1.material} />
        <mesh name="Text_cell046_2" geometry={nodes.Text_cell046_2.geometry} material={nodes.Text_cell046_2.material} />
      </group>
      <group name="Text_cell048" position={[1.82, 1.18, -0.125]}>
        <mesh name="Text_cell047_1" geometry={nodes.Text_cell047_1.geometry} material={nodes.Text_cell047_1.material} />
        <mesh name="Text_cell047_2" geometry={nodes.Text_cell047_2.geometry} material={nodes.Text_cell047_2.material} />
      </group>
      <group name="Text_cell049" position={[1.609, 0.191, -0.137]}>
        <mesh name="Text_cell048_1" geometry={nodes.Text_cell048_1.geometry} material={nodes.Text_cell048_1.material} />
        <mesh name="Text_cell048_2" geometry={nodes.Text_cell048_2.geometry} material={nodes.Text_cell048_2.material} />
      </group>
      <group name="Text_cell050" position={[1.903, 0.461, -0.347]}>
        <mesh name="Text_cell049_1" geometry={nodes.Text_cell049_1.geometry} material={nodes.Text_cell049_1.material} />
        <mesh name="Text_cell049_2" geometry={nodes.Text_cell049_2.geometry} material={nodes.Text_cell049_2.material} />
      </group>
      <group name="Text_cell051" position={[2.056, 1.269, -0.123]}>
        <mesh name="Text_cell050_1" geometry={nodes.Text_cell050_1.geometry} material={nodes.Text_cell050_1.material} />
        <mesh name="Text_cell050_2" geometry={nodes.Text_cell050_2.geometry} material={nodes.Text_cell050_2.material} />
      </group>
      <group name="Text_cell052" position={[1.323, -0.091, -0.327]}>
        <mesh name="Text_cell051_1" geometry={nodes.Text_cell051_1.geometry} material={nodes.Text_cell051_1.material} />
        <mesh name="Text_cell051_2" geometry={nodes.Text_cell051_2.geometry} material={nodes.Text_cell051_2.material} />
      </group>
      <group name="Text_cell053" position={[1.623, 0.213, -0.313]}>
        <mesh name="Text_cell052_1" geometry={nodes.Text_cell052_1.geometry} material={nodes.Text_cell052_1.material} />
        <mesh name="Text_cell052_2" geometry={nodes.Text_cell052_2.geometry} material={nodes.Text_cell052_2.material} />
      </group>
      <group name="Text_cell054" position={[0.537, -1.072, -0.361]}>
        <mesh name="Text_cell053_1" geometry={nodes.Text_cell053_1.geometry} material={nodes.Text_cell053_1.material} />
        <mesh name="Text_cell053_2" geometry={nodes.Text_cell053_2.geometry} material={nodes.Text_cell053_2.material} />
      </group>
      <group name="Text_cell055" position={[2.237, 0.621, -0.349]}>
        <mesh name="Text_cell054_1" geometry={nodes.Text_cell054_1.geometry} material={nodes.Text_cell054_1.material} />
        <mesh name="Text_cell054_2" geometry={nodes.Text_cell054_2.geometry} material={nodes.Text_cell054_2.material} />
      </group>
      <group name="Text_cell056" position={[0.343, 1.556, -0.138]}>
        <mesh name="Text_cell055_1" geometry={nodes.Text_cell055_1.geometry} material={nodes.Text_cell055_1.material} />
        <mesh name="Text_cell055_2" geometry={nodes.Text_cell055_2.geometry} material={nodes.Text_cell055_2.material} />
      </group>
      <group name="Text_cell057" position={[1.201, 1.376, -0.153]}>
        <mesh name="Text_cell056_1" geometry={nodes.Text_cell056_1.geometry} material={nodes.Text_cell056_1.material} />
        <mesh name="Text_cell056_2" geometry={nodes.Text_cell056_2.geometry} material={nodes.Text_cell056_2.material} />
      </group>
      <group name="Text_cell058" position={[0.656, -0.03, -0.341]}>
        <mesh name="Text_cell057_1" geometry={nodes.Text_cell057_1.geometry} material={nodes.Text_cell057_1.material} />
        <mesh name="Text_cell057_2" geometry={nodes.Text_cell057_2.geometry} material={nodes.Text_cell057_2.material} />
      </group>
      <group name="Text_cell059" position={[2.158, 0.416, -0.329]}>
        <mesh name="Text_cell058_1" geometry={nodes.Text_cell058_1.geometry} material={nodes.Text_cell058_1.material} />
        <mesh name="Text_cell058_2" geometry={nodes.Text_cell058_2.geometry} material={nodes.Text_cell058_2.material} />
      </group>
      <group name="Text_cell060" position={[2.234, 0.62, -0.139]}>
        <mesh name="Text_cell059_1" geometry={nodes.Text_cell059_1.geometry} material={nodes.Text_cell059_1.material} />
        <mesh name="Text_cell059_2" geometry={nodes.Text_cell059_2.geometry} material={nodes.Text_cell059_2.material} />
      </group>
      <group name="Text_cell061" position={[1.3, 0.155, -0.332]}>
        <mesh name="Text_cell060_1" geometry={nodes.Text_cell060_1.geometry} material={nodes.Text_cell060_1.material} />
        <mesh name="Text_cell060_2" geometry={nodes.Text_cell060_2.geometry} material={nodes.Text_cell060_2.material} />
      </group>
      <group name="Text_cell062" position={[1.165, 1.634, -0.128]}>
        <mesh name="Text_cell061_1" geometry={nodes.Text_cell061_1.geometry} material={nodes.Text_cell061_1.material} />
        <mesh name="Text_cell061_2" geometry={nodes.Text_cell061_2.geometry} material={nodes.Text_cell061_2.material} />
      </group>
      <group name="Text_cell063" position={[1.423, 0.14, -0.145]}>
        <mesh name="Text_cell062_1" geometry={nodes.Text_cell062_1.geometry} material={nodes.Text_cell062_1.material} />
        <mesh name="Text_cell062_2" geometry={nodes.Text_cell062_2.geometry} material={nodes.Text_cell062_2.material} />
      </group>
      <group name="Text_cell064" position={[1.885, 1.438, -0.131]}>
        <mesh name="Text_cell063_1" geometry={nodes.Text_cell063_1.geometry} material={nodes.Text_cell063_1.material} />
        <mesh name="Text_cell063_2" geometry={nodes.Text_cell063_2.geometry} material={nodes.Text_cell063_2.material} />
      </group>
      <group name="Text_cell065" position={[1.617, 1.328, -0.32]}>
        <mesh name="Text_cell064_1" geometry={nodes.Text_cell064_1.geometry} material={nodes.Text_cell064_1.material} />
        <mesh name="Text_cell064_2" geometry={nodes.Text_cell064_2.geometry} material={nodes.Text_cell064_2.material} />
      </group>
      <group name="Text_cell066" position={[1.939, 0.478, -0.136]}>
        <mesh name="Text_cell065_1" geometry={nodes.Text_cell065_1.geometry} material={nodes.Text_cell065_1.material} />
        <mesh name="Text_cell065_2" geometry={nodes.Text_cell065_2.geometry} material={nodes.Text_cell065_2.material} />
      </group>
      <group name="Text_cell067" position={[1.946, 0.119, -0.327]}>
        <mesh name="Text_cell066_1" geometry={nodes.Text_cell066_1.geometry} material={nodes.Text_cell066_1.material} />
        <mesh name="Text_cell066_2" geometry={nodes.Text_cell066_2.geometry} material={nodes.Text_cell066_2.material} />
      </group>
      <group name="Text_cell068" position={[1.494, 1.361, -0.135]}>
        <mesh name="Text_cell067_1" geometry={nodes.Text_cell067_1.geometry} material={nodes.Text_cell067_1.material} />
        <mesh name="Text_cell067_2" geometry={nodes.Text_cell067_2.geometry} material={nodes.Text_cell067_2.material} />
      </group>
      <group name="Text_cell069" position={[2.208, 0.509, -0.353]}>
        <mesh name="Text_cell068_1" geometry={nodes.Text_cell068_1.geometry} material={nodes.Text_cell068_1.material} />
        <mesh name="Text_cell068_2" geometry={nodes.Text_cell068_2.geometry} material={nodes.Text_cell068_2.material} />
      </group>
      <group name="Text_cell070" position={[1.517, 0.153, -0.337]}>
        <mesh name="Text_cell069_1" geometry={nodes.Text_cell069_1.geometry} material={nodes.Text_cell069_1.material} />
        <mesh name="Text_cell069_2" geometry={nodes.Text_cell069_2.geometry} material={nodes.Text_cell069_2.material} />
      </group>
      <group name="Text_cell071" position={[1.47, 1.603, -0.322]}>
        <mesh name="Text_cell070_1" geometry={nodes.Text_cell070_1.geometry} material={nodes.Text_cell070_1.material} />
        <mesh name="Text_cell070_2" geometry={nodes.Text_cell070_2.geometry} material={nodes.Text_cell070_2.material} />
      </group>
      <group name="Text_cell072" position={[1.845, 0.33, -0.33]}>
        <mesh name="Text_cell071_1" geometry={nodes.Text_cell071_1.geometry} material={nodes.Text_cell071_1.material} />
        <mesh name="Text_cell071_2" geometry={nodes.Text_cell071_2.geometry} material={nodes.Text_cell071_2.material} />
      </group>
      <group name="Text_cell073" position={[2.213, 0.75, -0.351]}>
        <mesh name="Text_cell072_1" geometry={nodes.Text_cell072_1.geometry} material={nodes.Text_cell072_1.material} />
        <mesh name="Text_cell072_2" geometry={nodes.Text_cell072_2.geometry} material={nodes.Text_cell072_2.material} />
      </group>
      <group name="Text_cell074" position={[2.217, 0.752, -0.146]}>
        <mesh name="Text_cell073_1" geometry={nodes.Text_cell073_1.geometry} material={nodes.Text_cell073_1.material} />
        <mesh name="Text_cell073_2" geometry={nodes.Text_cell073_2.geometry} material={nodes.Text_cell073_2.material} />
      </group>
      <group name="Text_cell075" position={[1.923, 1.44, -0.328]}>
        <mesh name="Text_cell074_1" geometry={nodes.Text_cell074_1.geometry} material={nodes.Text_cell074_1.material} />
        <mesh name="Text_cell074_2" geometry={nodes.Text_cell074_2.geometry} material={nodes.Text_cell074_2.material} />
      </group>
      <group name="Text_cell076" position={[0.326, -1.141, -0.13]}>
        <mesh name="Text_cell075_1" geometry={nodes.Text_cell075_1.geometry} material={nodes.Text_cell075_1.material} />
        <mesh name="Text_cell075_2" geometry={nodes.Text_cell075_2.geometry} material={nodes.Text_cell075_2.material} />
      </group>
      <group name="Text_cell077" position={[2.124, 0.314, -0.331]}>
        <mesh name="Text_cell076_1" geometry={nodes.Text_cell076_1.geometry} material={nodes.Text_cell076_1.material} />
        <mesh name="Text_cell076_2" geometry={nodes.Text_cell076_2.geometry} material={nodes.Text_cell076_2.material} />
      </group>
      <group name="Text_cell078" position={[1.655, 1.559, -0.336]}>
        <mesh name="Text_cell077_1" geometry={nodes.Text_cell077_1.geometry} material={nodes.Text_cell077_1.material} />
        <mesh name="Text_cell077_2" geometry={nodes.Text_cell077_2.geometry} material={nodes.Text_cell077_2.material} />
      </group>
      <group name="Text_cell079" position={[0.643, 1.291, -0.156]}>
        <mesh name="Text_cell078_1" geometry={nodes.Text_cell078_1.geometry} material={nodes.Text_cell078_1.material} />
        <mesh name="Text_cell078_2" geometry={nodes.Text_cell078_2.geometry} material={nodes.Text_cell078_2.material} />
      </group>
      <group name="Text_cell080" position={[0.574, -0.661, -0.262]}>
        <mesh name="Text_cell079_1" geometry={nodes.Text_cell079_1.geometry} material={nodes.Text_cell079_1.material} />
        <mesh name="Text_cell079_2" geometry={nodes.Text_cell079_2.geometry} material={nodes.Text_cell079_2.material} />
      </group>
      <group name="Text001_cell" position={[-2.212, 0.51, -0.188]}>
        <mesh name="Text001_cell082_1" geometry={nodes.Text001_cell082_1.geometry} material={nodes.Text001_cell082_1.material} />
        <mesh name="Text001_cell082_2" geometry={nodes.Text001_cell082_2.geometry} material={nodes.Text001_cell082_2.material} />
      </group>
      <group name="Text001_cell001" position={[-1.873, 1.116, -0.131]}>
        <mesh name="Text001_cell083" geometry={nodes.Text001_cell083.geometry} material={nodes.Text001_cell083.material} />
        <mesh name="Text001_cell083_1" geometry={nodes.Text001_cell083_1.geometry} material={nodes.Text001_cell083_1.material} />
      </group>
      <group name="Text001_cell002" position={[-1.923, 0.997, -0.119]}>
        <mesh name="Text001_cell001_1" geometry={nodes.Text001_cell001_1.geometry} material={nodes.Text001_cell001_1.material} />
        <mesh name="Text001_cell001_2" geometry={nodes.Text001_cell001_2.geometry} material={nodes.Text001_cell001_2.material} />
      </group>
      <group name="Text001_cell003" position={[-1.876, 0.403, -0.341]}>
        <mesh name="Text001_cell002_1" geometry={nodes.Text001_cell002_1.geometry} material={nodes.Text001_cell002_1.material} />
        <mesh name="Text001_cell002_2" geometry={nodes.Text001_cell002_2.geometry} material={nodes.Text001_cell002_2.material} />
      </group>
      <group name="Text001_cell004" position={[-2.095, 1.273, -0.127]}>
        <mesh name="Text001_cell003_1" geometry={nodes.Text001_cell003_1.geometry} material={nodes.Text001_cell003_1.material} />
        <mesh name="Text001_cell003_2" geometry={nodes.Text001_cell003_2.geometry} material={nodes.Text001_cell003_2.material} />
      </group>
      <group name="Text001_cell005" position={[-1.651, -0.004, -0.145]}>
        <mesh name="Text001_cell004_1" geometry={nodes.Text001_cell004_1.geometry} material={nodes.Text001_cell004_1.material} />
        <mesh name="Text001_cell004_2" geometry={nodes.Text001_cell004_2.geometry} material={nodes.Text001_cell004_2.material} />
      </group>
      <group name="Text001_cell006" position={[-1.039, -0.126, -0.225]}>
        <mesh name="Text001_cell005_1" geometry={nodes.Text001_cell005_1.geometry} material={nodes.Text001_cell005_1.material} />
        <mesh name="Text001_cell005_2" geometry={nodes.Text001_cell005_2.geometry} material={nodes.Text001_cell005_2.material} />
      </group>
      <group name="Text001_cell007" position={[-1.112, 0.092, -0.346]}>
        <mesh name="Text001_cell006_1" geometry={nodes.Text001_cell006_1.geometry} material={nodes.Text001_cell006_1.material} />
        <mesh name="Text001_cell006_2" geometry={nodes.Text001_cell006_2.geometry} material={nodes.Text001_cell006_2.material} />
      </group>
      <group name="Text001_cell008" position={[-1.812, 0.02, -0.172]}>
        <mesh name="Text001_cell007_1" geometry={nodes.Text001_cell007_1.geometry} material={nodes.Text001_cell007_1.material} />
        <mesh name="Text001_cell007_2" geometry={nodes.Text001_cell007_2.geometry} material={nodes.Text001_cell007_2.material} />
      </group>
      <group name="Text001_cell009" position={[-1.82, 0.318, -0.325]}>
        <mesh name="Text001_cell008_1" geometry={nodes.Text001_cell008_1.geometry} material={nodes.Text001_cell008_1.material} />
        <mesh name="Text001_cell008_2" geometry={nodes.Text001_cell008_2.geometry} material={nodes.Text001_cell008_2.material} />
      </group>
      <group name="Text001_cell010" position={[-2.123, 1.173, -0.353]}>
        <mesh name="Text001_cell009_1" geometry={nodes.Text001_cell009_1.geometry} material={nodes.Text001_cell009_1.material} />
        <mesh name="Text001_cell009_2" geometry={nodes.Text001_cell009_2.geometry} material={nodes.Text001_cell009_2.material} />
      </group>
      <group name="Text001_cell011" position={[-1.875, 1.113, -0.34]}>
        <mesh name="Text001_cell010_1" geometry={nodes.Text001_cell010_1.geometry} material={nodes.Text001_cell010_1.material} />
        <mesh name="Text001_cell010_2" geometry={nodes.Text001_cell010_2.geometry} material={nodes.Text001_cell010_2.material} />
      </group>
      <group name="Text001_cell012" position={[-1.531, -0.085, -0.169]}>
        <mesh name="Text001_cell011_1" geometry={nodes.Text001_cell011_1.geometry} material={nodes.Text001_cell011_1.material} />
        <mesh name="Text001_cell011_2" geometry={nodes.Text001_cell011_2.geometry} material={nodes.Text001_cell011_2.material} />
      </group>
      <group name="Text001_cell013" position={[-1.532, 0.136, -0.305]}>
        <mesh name="Text001_cell012_1" geometry={nodes.Text001_cell012_1.geometry} material={nodes.Text001_cell012_1.material} />
        <mesh name="Text001_cell012_2" geometry={nodes.Text001_cell012_2.geometry} material={nodes.Text001_cell012_2.material} />
      </group>
      <group name="Text001_cell014" position={[-0.328, 1.504, -0.325]}>
        <mesh name="Text001_cell013_1" geometry={nodes.Text001_cell013_1.geometry} material={nodes.Text001_cell013_1.material} />
        <mesh name="Text001_cell013_2" geometry={nodes.Text001_cell013_2.geometry} material={nodes.Text001_cell013_2.material} />
      </group>
      <group name="Text001_cell015" position={[-1.617, 0.175, -0.327]}>
        <mesh name="Text001_cell014_1" geometry={nodes.Text001_cell014_1.geometry} material={nodes.Text001_cell014_1.material} />
        <mesh name="Text001_cell014_2" geometry={nodes.Text001_cell014_2.geometry} material={nodes.Text001_cell014_2.material} />
      </group>
      <group name="Text001_cell016" position={[-2.229, 0.843, -0.332]}>
        <mesh name="Text001_cell015_1" geometry={nodes.Text001_cell015_1.geometry} material={nodes.Text001_cell015_1.material} />
        <mesh name="Text001_cell015_2" geometry={nodes.Text001_cell015_2.geometry} material={nodes.Text001_cell015_2.material} />
      </group>
      <group name="Text001_cell017" position={[-1.433, 0.162, -0.147]}>
        <mesh name="Text001_cell016_1" geometry={nodes.Text001_cell016_1.geometry} material={nodes.Text001_cell016_1.material} />
        <mesh name="Text001_cell016_2" geometry={nodes.Text001_cell016_2.geometry} material={nodes.Text001_cell016_2.material} />
      </group>
      <group name="Text001_cell018" position={[-0.521, 1.593, -0.126]}>
        <mesh name="Text001_cell017_1" geometry={nodes.Text001_cell017_1.geometry} material={nodes.Text001_cell017_1.material} />
        <mesh name="Text001_cell017_2" geometry={nodes.Text001_cell017_2.geometry} material={nodes.Text001_cell017_2.material} />
      </group>
      <group name="Text001_cell019" position={[-2.091, 1.281, -0.348]}>
        <mesh name="Text001_cell018_1" geometry={nodes.Text001_cell018_1.geometry} material={nodes.Text001_cell018_1.material} />
        <mesh name="Text001_cell018_2" geometry={nodes.Text001_cell018_2.geometry} material={nodes.Text001_cell018_2.material} />
      </group>
      <group name="Text001_cell020" position={[-0.31, -1.023, -0.145]}>
        <mesh name="Text001_cell019_1" geometry={nodes.Text001_cell019_1.geometry} material={nodes.Text001_cell019_1.material} />
        <mesh name="Text001_cell019_2" geometry={nodes.Text001_cell019_2.geometry} material={nodes.Text001_cell019_2.material} />
      </group>
      <group name="Text001_cell021" position={[-1.932, 0.999, -0.341]}>
        <mesh name="Text001_cell020_1" geometry={nodes.Text001_cell020_1.geometry} material={nodes.Text001_cell020_1.material} />
        <mesh name="Text001_cell020_2" geometry={nodes.Text001_cell020_2.geometry} material={nodes.Text001_cell020_2.material} />
      </group>
      <group name="Text001_cell022" position={[-2.192, 1.082, -0.342]}>
        <mesh name="Text001_cell021_1" geometry={nodes.Text001_cell021_1.geometry} material={nodes.Text001_cell021_1.material} />
        <mesh name="Text001_cell021_2" geometry={nodes.Text001_cell021_2.geometry} material={nodes.Text001_cell021_2.material} />
      </group>
      <group name="Text001_cell023" position={[-1.787, 0.012, -0.337]}>
        <mesh name="Text001_cell022_1" geometry={nodes.Text001_cell022_1.geometry} material={nodes.Text001_cell022_1.material} />
        <mesh name="Text001_cell022_2" geometry={nodes.Text001_cell022_2.geometry} material={nodes.Text001_cell022_2.material} />
      </group>
      <group name="Text001_cell024" position={[-1.038, 1.57, -0.154]}>
        <mesh name="Text001_cell023_1" geometry={nodes.Text001_cell023_1.geometry} material={nodes.Text001_cell023_1.material} />
        <mesh name="Text001_cell023_2" geometry={nodes.Text001_cell023_2.geometry} material={nodes.Text001_cell023_2.material} />
      </group>
      <group name="Text001_cell025" position={[-1.736, 1.276, -0.128]}>
        <mesh name="Text001_cell024_1" geometry={nodes.Text001_cell024_1.geometry} material={nodes.Text001_cell024_1.material} />
        <mesh name="Text001_cell024_2" geometry={nodes.Text001_cell024_2.geometry} material={nodes.Text001_cell024_2.material} />
      </group>
      <group name="Text001_cell026" position={[-1.805, 1.194, -0.342]}>
        <mesh name="Text001_cell025_1" geometry={nodes.Text001_cell025_1.geometry} material={nodes.Text001_cell025_1.material} />
        <mesh name="Text001_cell025_2" geometry={nodes.Text001_cell025_2.geometry} material={nodes.Text001_cell025_2.material} />
      </group>
      <group name="Text001_cell027" position={[-1.803, 0.342, -0.128]}>
        <mesh name="Text001_cell026_1" geometry={nodes.Text001_cell026_1.geometry} material={nodes.Text001_cell026_1.material} />
        <mesh name="Text001_cell026_2" geometry={nodes.Text001_cell026_2.geometry} material={nodes.Text001_cell026_2.material} />
      </group>
      <group name="Text001_cell028" position={[-1.987, 0.557, -0.332]}>
        <mesh name="Text001_cell027_1" geometry={nodes.Text001_cell027_1.geometry} material={nodes.Text001_cell027_1.material} />
        <mesh name="Text001_cell027_2" geometry={nodes.Text001_cell027_2.geometry} material={nodes.Text001_cell027_2.material} />
      </group>
      <group name="Text001_cell029" position={[-1.586, 1.319, -0.144]}>
        <mesh name="Text001_cell028_1" geometry={nodes.Text001_cell028_1.geometry} material={nodes.Text001_cell028_1.material} />
        <mesh name="Text001_cell028_2" geometry={nodes.Text001_cell028_2.geometry} material={nodes.Text001_cell028_2.material} />
      </group>
      <group name="Text001_cell030" position={[-2.021, 1.354, -0.333]}>
        <mesh name="Text001_cell029_1" geometry={nodes.Text001_cell029_1.geometry} material={nodes.Text001_cell029_1.material} />
        <mesh name="Text001_cell029_2" geometry={nodes.Text001_cell029_2.geometry} material={nodes.Text001_cell029_2.material} />
      </group>
      <group name="Text001_cell031" position={[-1.79, 1.493, -0.341]}>
        <mesh name="Text001_cell030_1" geometry={nodes.Text001_cell030_1.geometry} material={nodes.Text001_cell030_1.material} />
        <mesh name="Text001_cell030_2" geometry={nodes.Text001_cell030_2.geometry} material={nodes.Text001_cell030_2.material} />
      </group>
      <group name="Text001_cell032" position={[-1.809, 1.201, -0.122]}>
        <mesh name="Text001_cell031_1" geometry={nodes.Text001_cell031_1.geometry} material={nodes.Text001_cell031_1.material} />
        <mesh name="Text001_cell031_2" geometry={nodes.Text001_cell031_2.geometry} material={nodes.Text001_cell031_2.material} />
      </group>
      <group name="Text001_cell033" position={[-2.124, 1.16, -0.123]}>
        <mesh name="Text001_cell032_1" geometry={nodes.Text001_cell032_1.geometry} material={nodes.Text001_cell032_1.material} />
        <mesh name="Text001_cell032_2" geometry={nodes.Text001_cell032_2.geometry} material={nodes.Text001_cell032_2.material} />
      </group>
      <group name="Text001_cell034" position={[-1.587, 1.352, -0.347]}>
        <mesh name="Text001_cell033_1" geometry={nodes.Text001_cell033_1.geometry} material={nodes.Text001_cell033_1.material} />
        <mesh name="Text001_cell033_2" geometry={nodes.Text001_cell033_2.geometry} material={nodes.Text001_cell033_2.material} />
      </group>
      <group name="Text001_cell035" position={[-2.115, 0.296, -0.14]}>
        <mesh name="Text001_cell034_1" geometry={nodes.Text001_cell034_1.geometry} material={nodes.Text001_cell034_1.material} />
        <mesh name="Text001_cell034_2" geometry={nodes.Text001_cell034_2.geometry} material={nodes.Text001_cell034_2.material} />
      </group>
      <group name="Text001_cell036" position={[-1.944, 0.824, -0.128]}>
        <mesh name="Text001_cell035_1" geometry={nodes.Text001_cell035_1.geometry} material={nodes.Text001_cell035_1.material} />
        <mesh name="Text001_cell035_2" geometry={nodes.Text001_cell035_2.geometry} material={nodes.Text001_cell035_2.material} />
      </group>
      <group name="Text001_cell037" position={[-1.378, -0.087, -0.146]}>
        <mesh name="Text001_cell036_1" geometry={nodes.Text001_cell036_1.geometry} material={nodes.Text001_cell036_1.material} />
        <mesh name="Text001_cell036_2" geometry={nodes.Text001_cell036_2.geometry} material={nodes.Text001_cell036_2.material} />
      </group>
      <group name="Text001_cell038" position={[-0.65, -0.092, -0.232]}>
        <mesh name="Text001_cell037_1" geometry={nodes.Text001_cell037_1.geometry} material={nodes.Text001_cell037_1.material} />
        <mesh name="Text001_cell037_2" geometry={nodes.Text001_cell037_2.geometry} material={nodes.Text001_cell037_2.material} />
      </group>
      <group name="Text001_cell039" position={[-1.307, 1.626, -0.356]}>
        <mesh name="Text001_cell038_1" geometry={nodes.Text001_cell038_1.geometry} material={nodes.Text001_cell038_1.material} />
        <mesh name="Text001_cell038_2" geometry={nodes.Text001_cell038_2.geometry} material={nodes.Text001_cell038_2.material} />
      </group>
      <group name="Text001_cell040" position={[-2.127, 0.431, -0.145]}>
        <mesh name="Text001_cell039_1" geometry={nodes.Text001_cell039_1.geometry} material={nodes.Text001_cell039_1.material} />
        <mesh name="Text001_cell039_2" geometry={nodes.Text001_cell039_2.geometry} material={nodes.Text001_cell039_2.material} />
      </group>
      <group name="Text001_cell041" position={[-1.687, 0.23, -0.143]}>
        <mesh name="Text001_cell040_1" geometry={nodes.Text001_cell040_1.geometry} material={nodes.Text001_cell040_1.material} />
        <mesh name="Text001_cell040_2" geometry={nodes.Text001_cell040_2.geometry} material={nodes.Text001_cell040_2.material} />
      </group>
      <group name="Text001_cell042" position={[-1.608, 1.563, -0.315]}>
        <mesh name="Text001_cell041_1" geometry={nodes.Text001_cell041_1.geometry} material={nodes.Text001_cell041_1.material} />
        <mesh name="Text001_cell041_2" geometry={nodes.Text001_cell041_2.geometry} material={nodes.Text001_cell041_2.material} />
      </group>
      <group name="Text001_cell043" position={[-1.959, 0.673, -0.326]}>
        <mesh name="Text001_cell042_1" geometry={nodes.Text001_cell042_1.geometry} material={nodes.Text001_cell042_1.material} />
        <mesh name="Text001_cell042_2" geometry={nodes.Text001_cell042_2.geometry} material={nodes.Text001_cell042_2.material} />
      </group>
      <group name="Text001_cell044" position={[-1.928, 1.428, -0.337]}>
        <mesh name="Text001_cell043_1" geometry={nodes.Text001_cell043_1.geometry} material={nodes.Text001_cell043_1.material} />
        <mesh name="Text001_cell043_2" geometry={nodes.Text001_cell043_2.geometry} material={nodes.Text001_cell043_2.material} />
      </group>
      <group name="Text001_cell045" position={[-1.952, 0.803, -0.344]}>
        <mesh name="Text001_cell044_1" geometry={nodes.Text001_cell044_1.geometry} material={nodes.Text001_cell044_1.material} />
        <mesh name="Text001_cell044_2" geometry={nodes.Text001_cell044_2.geometry} material={nodes.Text001_cell044_2.material} />
      </group>
      <group name="Text001_cell046" position={[-2.205, 0.656, -0.344]}>
        <mesh name="Text001_cell045_1" geometry={nodes.Text001_cell045_1.geometry} material={nodes.Text001_cell045_1.material} />
        <mesh name="Text001_cell045_2" geometry={nodes.Text001_cell045_2.geometry} material={nodes.Text001_cell045_2.material} />
      </group>
      <group name="Text001_cell047" position={[-2.005, 1.356, -0.131]}>
        <mesh name="Text001_cell046_1" geometry={nodes.Text001_cell046_1.geometry} material={nodes.Text001_cell046_1.material} />
        <mesh name="Text001_cell046_2" geometry={nodes.Text001_cell046_2.geometry} material={nodes.Text001_cell046_2.material} />
      </group>
      <group name="Text001_cell048" position={[-1.361, 1.356, -0.118]}>
        <mesh name="Text001_cell047_1" geometry={nodes.Text001_cell047_1.geometry} material={nodes.Text001_cell047_1.material} />
        <mesh name="Text001_cell047_2" geometry={nodes.Text001_cell047_2.geometry} material={nodes.Text001_cell047_2.material} />
      </group>
      <group name="Text001_cell049" position={[-1.918, 1.413, -0.122]}>
        <mesh name="Text001_cell048_1" geometry={nodes.Text001_cell048_1.geometry} material={nodes.Text001_cell048_1.material} />
        <mesh name="Text001_cell048_2" geometry={nodes.Text001_cell048_2.geometry} material={nodes.Text001_cell048_2.material} />
      </group>
      <group name="Text001_cell050" position={[-1.146, 0.128, -0.123]}>
        <mesh name="Text001_cell049_1" geometry={nodes.Text001_cell049_1.geometry} material={nodes.Text001_cell049_1.material} />
        <mesh name="Text001_cell049_2" geometry={nodes.Text001_cell049_2.geometry} material={nodes.Text001_cell049_2.material} />
      </group>
      <group name="Text001_cell051" position={[-1.348, -0.115, -0.324]}>
        <mesh name="Text001_cell050_1" geometry={nodes.Text001_cell050_1.geometry} material={nodes.Text001_cell050_1.material} />
        <mesh name="Text001_cell050_2" geometry={nodes.Text001_cell050_2.geometry} material={nodes.Text001_cell050_2.material} />
      </group>
      <group name="Text001_cell052" position={[-2.194, 1.079, -0.127]}>
        <mesh name="Text001_cell051_1" geometry={nodes.Text001_cell051_1.geometry} material={nodes.Text001_cell051_1.material} />
        <mesh name="Text001_cell051_2" geometry={nodes.Text001_cell051_2.geometry} material={nodes.Text001_cell051_2.material} />
      </group>
      <group name="Text001_cell053" position={[-1.956, 0.615, -0.133]}>
        <mesh name="Text001_cell052_1" geometry={nodes.Text001_cell052_1.geometry} material={nodes.Text001_cell052_1.material} />
        <mesh name="Text001_cell052_2" geometry={nodes.Text001_cell052_2.geometry} material={nodes.Text001_cell052_2.material} />
      </group>
      <group name="Text001_cell054" position={[-2.228, 0.732, -0.13]}>
        <mesh name="Text001_cell053_1" geometry={nodes.Text001_cell053_1.geometry} material={nodes.Text001_cell053_1.material} />
        <mesh name="Text001_cell053_2" geometry={nodes.Text001_cell053_2.geometry} material={nodes.Text001_cell053_2.material} />
      </group>
      <group name="Text001_cell055" position={[-1.951, 0.115, -0.344]}>
        <mesh name="Text001_cell054_1" geometry={nodes.Text001_cell054_1.geometry} material={nodes.Text001_cell054_1.material} />
        <mesh name="Text001_cell054_2" geometry={nodes.Text001_cell054_2.geometry} material={nodes.Text001_cell054_2.material} />
      </group>
      <group name="Text001_cell056" position={[-1.456, 1.351, -0.328]}>
        <mesh name="Text001_cell055_1" geometry={nodes.Text001_cell055_1.geometry} material={nodes.Text001_cell055_1.material} />
        <mesh name="Text001_cell055_2" geometry={nodes.Text001_cell055_2.geometry} material={nodes.Text001_cell055_2.material} />
      </group>
      <group name="Text001_cell057" position={[-0.584, -1.165, -0.353]}>
        <mesh name="Text001_cell056_1" geometry={nodes.Text001_cell056_1.geometry} material={nodes.Text001_cell056_1.material} />
        <mesh name="Text001_cell056_2" geometry={nodes.Text001_cell056_2.geometry} material={nodes.Text001_cell056_2.material} />
      </group>
      <group name="Text001_cell058" position={[-1.667, 1.546, -0.152]}>
        <mesh name="Text001_cell057_1" geometry={nodes.Text001_cell057_1.geometry} material={nodes.Text001_cell057_1.material} />
        <mesh name="Text001_cell057_2" geometry={nodes.Text001_cell057_2.geometry} material={nodes.Text001_cell057_2.material} />
      </group>
      <group name="Text001_cell059" position={[-0.693, 1.316, -0.259]}>
        <mesh name="Text001_cell058_1" geometry={nodes.Text001_cell058_1.geometry} material={nodes.Text001_cell058_1.material} />
        <mesh name="Text001_cell058_2" geometry={nodes.Text001_cell058_2.geometry} material={nodes.Text001_cell058_2.material} />
      </group>
      <group name="Text001_cell060" position={[-1.441, 0.131, -0.331]}>
        <mesh name="Text001_cell059_1" geometry={nodes.Text001_cell059_1.geometry} material={nodes.Text001_cell059_1.material} />
        <mesh name="Text001_cell059_2" geometry={nodes.Text001_cell059_2.geometry} material={nodes.Text001_cell059_2.material} />
      </group>
      <group name="Text001_cell061" position={[-1.952, 0.757, -0.139]}>
        <mesh name="Text001_cell060_1" geometry={nodes.Text001_cell060_1.geometry} material={nodes.Text001_cell060_1.material} />
        <mesh name="Text001_cell060_2" geometry={nodes.Text001_cell060_2.geometry} material={nodes.Text001_cell060_2.material} />
      </group>
      <group name="Text001_cell062" position={[-1.916, 0.481, -0.331]}>
        <mesh name="Text001_cell061_1" geometry={nodes.Text001_cell061_1.geometry} material={nodes.Text001_cell061_1.material} />
        <mesh name="Text001_cell061_2" geometry={nodes.Text001_cell061_2.geometry} material={nodes.Text001_cell061_2.material} />
      </group>
      <group name="Text001_cell063" position={[-1.185, 1.382, -0.286]}>
        <mesh name="Text001_cell062_1" geometry={nodes.Text001_cell062_1.geometry} material={nodes.Text001_cell062_1.material} />
        <mesh name="Text001_cell062_2" geometry={nodes.Text001_cell062_2.geometry} material={nodes.Text001_cell062_2.material} />
      </group>
      <group name="Text001_cell064" position={[-1.888, 0.436, -0.131]}>
        <mesh name="Text001_cell063_1" geometry={nodes.Text001_cell063_1.geometry} material={nodes.Text001_cell063_1.material} />
        <mesh name="Text001_cell063_2" geometry={nodes.Text001_cell063_2.geometry} material={nodes.Text001_cell063_2.material} />
      </group>
      <group name="Text001_cell065" position={[-0.575, -1.309, -0.147]}>
        <mesh name="Text001_cell064_1" geometry={nodes.Text001_cell064_1.geometry} material={nodes.Text001_cell064_1.material} />
        <mesh name="Text001_cell064_2" geometry={nodes.Text001_cell064_2.geometry} material={nodes.Text001_cell064_2.material} />
      </group>
      <group name="Text001_cell066" position={[-1.635, -0.061, -0.331]}>
        <mesh name="Text001_cell065_1" geometry={nodes.Text001_cell065_1.geometry} material={nodes.Text001_cell065_1.material} />
        <mesh name="Text001_cell065_2" geometry={nodes.Text001_cell065_2.geometry} material={nodes.Text001_cell065_2.material} />
      </group>
      <group name="Text001_cell067" position={[-2.232, 0.61, -0.161]}>
        <mesh name="Text001_cell066_1" geometry={nodes.Text001_cell066_1.geometry} material={nodes.Text001_cell066_1.material} />
        <mesh name="Text001_cell066_2" geometry={nodes.Text001_cell066_2.geometry} material={nodes.Text001_cell066_2.material} />
      </group>
      <group name="Text001_cell068" position={[-1.344, 0.15, -0.333]}>
        <mesh name="Text001_cell067_1" geometry={nodes.Text001_cell067_1.geometry} material={nodes.Text001_cell067_1.material} />
        <mesh name="Text001_cell067_2" geometry={nodes.Text001_cell067_2.geometry} material={nodes.Text001_cell067_2.material} />
      </group>
      <group name="Text001_cell069" position={[-1.672, 1.306, -0.332]}>
        <mesh name="Text001_cell068_1" geometry={nodes.Text001_cell068_1.geometry} material={nodes.Text001_cell068_1.material} />
        <mesh name="Text001_cell068_2" geometry={nodes.Text001_cell068_2.geometry} material={nodes.Text001_cell068_2.material} />
      </group>
      <group name="Text001_cell070" position={[-2.22, 0.846, -0.132]}>
        <mesh name="Text001_cell069_1" geometry={nodes.Text001_cell069_1.geometry} material={nodes.Text001_cell069_1.material} />
        <mesh name="Text001_cell069_2" geometry={nodes.Text001_cell069_2.geometry} material={nodes.Text001_cell069_2.material} />
      </group>
      <group name="Text001_cell071" position={[-2.209, 0.97, -0.333]}>
        <mesh name="Text001_cell070_1" geometry={nodes.Text001_cell070_1.geometry} material={nodes.Text001_cell070_1.material} />
        <mesh name="Text001_cell070_2" geometry={nodes.Text001_cell070_2.geometry} material={nodes.Text001_cell070_2.material} />
      </group>
      <group name="Text001_cell072" position={[-0.334, -1.098, -0.344]}>
        <mesh name="Text001_cell071_1" geometry={nodes.Text001_cell071_1.geometry} material={nodes.Text001_cell071_1.material} />
        <mesh name="Text001_cell071_2" geometry={nodes.Text001_cell071_2.geometry} material={nodes.Text001_cell071_2.material} />
      </group>
      <group name="Text001_cell073" position={[-1.991, 0.175, -0.15]}>
        <mesh name="Text001_cell072_1" geometry={nodes.Text001_cell072_1.geometry} material={nodes.Text001_cell072_1.material} />
        <mesh name="Text001_cell072_2" geometry={nodes.Text001_cell072_2.geometry} material={nodes.Text001_cell072_2.material} />
      </group>
      <group name="Text001_cell074" position={[-1.739, 1.241, -0.35]}>
        <mesh name="Text001_cell073_1" geometry={nodes.Text001_cell073_1.geometry} material={nodes.Text001_cell073_1.material} />
        <mesh name="Text001_cell073_2" geometry={nodes.Text001_cell073_2.geometry} material={nodes.Text001_cell073_2.material} />
      </group>
      <group name="Text001_cell075" position={[-1.7, 0.226, -0.334]}>
        <mesh name="Text001_cell074_1" geometry={nodes.Text001_cell074_1.geometry} material={nodes.Text001_cell074_1.material} />
        <mesh name="Text001_cell074_2" geometry={nodes.Text001_cell074_2.geometry} material={nodes.Text001_cell074_2.material} />
      </group>
      <group name="Text001_cell076" position={[-2.207, 0.971, -0.127]}>
        <mesh name="Text001_cell075_1" geometry={nodes.Text001_cell075_1.geometry} material={nodes.Text001_cell075_1.material} />
        <mesh name="Text001_cell075_2" geometry={nodes.Text001_cell075_2.geometry} material={nodes.Text001_cell075_2.material} />
      </group>
      <group name="Text001_cell077" position={[-2.126, 0.347, -0.337]}>
        <mesh name="Text001_cell076_1" geometry={nodes.Text001_cell076_1.geometry} material={nodes.Text001_cell076_1.material} />
        <mesh name="Text001_cell076_2" geometry={nodes.Text001_cell076_2.geometry} material={nodes.Text001_cell076_2.material} />
      </group>
      <group name="Text001_cell078" position={[-1.83, 1.491, -0.141]}>
        <mesh name="Text001_cell077_1" geometry={nodes.Text001_cell077_1.geometry} material={nodes.Text001_cell077_1.material} />
        <mesh name="Text001_cell077_2" geometry={nodes.Text001_cell077_2.geometry} material={nodes.Text001_cell077_2.material} />
      </group>
      <group name="Text001_cell079" position={[-1.925, 0.902, -0.364]}>
        <mesh name="Text001_cell078_1" geometry={nodes.Text001_cell078_1.geometry} material={nodes.Text001_cell078_1.material} />
        <mesh name="Text001_cell078_2" geometry={nodes.Text001_cell078_2.geometry} material={nodes.Text001_cell078_2.material} />
      </group>
      <group name="Text001_cell080" position={[-1.925, 0.9, -0.117]}>
        <mesh name="Text001_cell079_1" geometry={nodes.Text001_cell079_1.geometry} material={nodes.Text001_cell079_1.material} />
        <mesh name="Text001_cell079_2" geometry={nodes.Text001_cell079_2.geometry} material={nodes.Text001_cell079_2.material} />
      </group>
      <group name="Text001_cell081" position={[-1.464, 1.6, -0.146]}>
        <mesh name="Text001_cell080_1" geometry={nodes.Text001_cell080_1.geometry} material={nodes.Text001_cell080_1.material} />
        <mesh name="Text001_cell080_2" geometry={nodes.Text001_cell080_2.geometry} material={nodes.Text001_cell080_2.material} />
      </group>
      <group name="Text001_cell082" position={[-0.52, -0.679, -0.249]}>
        <mesh name="Text001_cell081_1" geometry={nodes.Text001_cell081_1.geometry} material={nodes.Text001_cell081_1.material} />
        <mesh name="Text001_cell081_2" geometry={nodes.Text001_cell081_2.geometry} material={nodes.Text001_cell081_2.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/../logoPP1.glb')
