/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\logoPP.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/logoPP.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Text_cell" position={[1.068, 1.033, 0.116]}>
          <mesh name="Text_cell082" geometry={nodes.Text_cell082.geometry} material={nodes.Text_cell082.material} />
          <mesh name="Text_cell082_1" geometry={nodes.Text_cell082_1.geometry} material={nodes.Text_cell082_1.material} />
        </group>
        <group name="Text_cell001" position={[0.887, 1.101, 0.11]}>
          <mesh name="Text_cell083" geometry={nodes.Text_cell083.geometry} material={nodes.Text_cell083.material} />
          <mesh name="Text_cell083_1" geometry={nodes.Text_cell083_1.geometry} material={nodes.Text_cell083_1.material} />
        </group>
        <group name="Text_cell002" position={[1.12, 1.251, 0.027]}>
          <mesh name="Text_cell001_1" geometry={nodes.Text_cell001_1.geometry} material={nodes.Text_cell001_1.material} />
          <mesh name="Text_cell001_2" geometry={nodes.Text_cell001_2.geometry} material={nodes.Text_cell001_2.material} />
        </group>
        <group name="Text_cell003" position={[1.056, 1.912, 0.171]}>
          <mesh name="Text_cell002_1" geometry={nodes.Text_cell002_1.geometry} material={nodes.Text_cell002_1.material} />
          <mesh name="Text_cell002_2" geometry={nodes.Text_cell002_2.geometry} material={nodes.Text_cell002_2.material} />
        </group>
        <group name="Text_cell004" position={[1.071, 1.743, 0.053]}>
          <mesh name="Text_cell003_1" geometry={nodes.Text_cell003_1.geometry} material={nodes.Text_cell003_1.material} />
          <mesh name="Text_cell003_2" geometry={nodes.Text_cell003_2.geometry} material={nodes.Text_cell003_2.material} />
        </group>
        <group name="Text_cell005" position={[0.309, 0.768, 0.098]}>
          <mesh name="Text_cell004_1" geometry={nodes.Text_cell004_1.geometry} material={nodes.Text_cell004_1.material} />
          <mesh name="Text_cell004_2" geometry={nodes.Text_cell004_2.geometry} material={nodes.Text_cell004_2.material} />
        </group>
        <group name="Text_cell006" position={[1.231, 1.78, 0.064]}>
          <mesh name="Text_cell005_1" geometry={nodes.Text_cell005_1.geometry} material={nodes.Text_cell005_1.material} />
          <mesh name="Text_cell005_2" geometry={nodes.Text_cell005_2.geometry} material={nodes.Text_cell005_2.material} />
        </group>
        <group name="Text_cell007" position={[1.183, 1.136, 0.016]}>
          <mesh name="Text_cell006_1" geometry={nodes.Text_cell006_1.geometry} material={nodes.Text_cell006_1.material} />
          <mesh name="Text_cell006_2" geometry={nodes.Text_cell006_2.geometry} material={nodes.Text_cell006_2.material} />
        </group>
        <group name="Text_cell008" position={[1.314, 1.438, 0.037]}>
          <mesh name="Text_cell007_1" geometry={nodes.Text_cell007_1.geometry} material={nodes.Text_cell007_1.material} />
          <mesh name="Text_cell007_2" geometry={nodes.Text_cell007_2.geometry} material={nodes.Text_cell007_2.material} />
        </group>
        <group name="Text_cell009" position={[0.846, 1.97, 0.069]}>
          <mesh name="Text_cell008_1" geometry={nodes.Text_cell008_1.geometry} material={nodes.Text_cell008_1.material} />
          <mesh name="Text_cell008_2" geometry={nodes.Text_cell008_2.geometry} material={nodes.Text_cell008_2.material} />
        </group>
        <group name="Text_cell010" position={[0.318, 0.241, 0.072]}>
          <mesh name="Text_cell009_1" geometry={nodes.Text_cell009_1.geometry} material={nodes.Text_cell009_1.material} />
          <mesh name="Text_cell009_2" geometry={nodes.Text_cell009_2.geometry} material={nodes.Text_cell009_2.material} />
        </group>
        <group name="Text_cell011" position={[0.981, 0.986, 0.115]}>
          <mesh name="Text_cell010_1" geometry={nodes.Text_cell010_1.geometry} material={nodes.Text_cell010_1.material} />
          <mesh name="Text_cell010_2" geometry={nodes.Text_cell010_2.geometry} material={nodes.Text_cell010_2.material} />
        </group>
        <group name="Text_cell012" position={[1.281, 1.267, 0.028]}>
          <mesh name="Text_cell011_1" geometry={nodes.Text_cell011_1.geometry} material={nodes.Text_cell011_1.material} />
          <mesh name="Text_cell011_2" geometry={nodes.Text_cell011_2.geometry} material={nodes.Text_cell011_2.material} />
        </group>
        <group name="Text_cell013" position={[0.907, 0.972, 0.018]}>
          <mesh name="Text_cell012_1" geometry={nodes.Text_cell012_1.geometry} material={nodes.Text_cell012_1.material} />
          <mesh name="Text_cell012_2" geometry={nodes.Text_cell012_2.geometry} material={nodes.Text_cell012_2.material} />
        </group>
        <group name="Text_cell014" position={[1.135, 1.869, 0.169]}>
          <mesh name="Text_cell013_1" geometry={nodes.Text_cell013_1.geometry} material={nodes.Text_cell013_1.material} />
          <mesh name="Text_cell013_2" geometry={nodes.Text_cell013_2.geometry} material={nodes.Text_cell013_2.material} />
        </group>
        <group name="Text_cell015" position={[0.864, 1.093, 0.023]}>
          <mesh name="Text_cell014_1" geometry={nodes.Text_cell014_1.geometry} material={nodes.Text_cell014_1.material} />
          <mesh name="Text_cell014_2" geometry={nodes.Text_cell014_2.geometry} material={nodes.Text_cell014_2.material} />
        </group>
        <group name="Text_cell016" position={[1.292, 1.583, 0.152]}>
          <mesh name="Text_cell015_1" geometry={nodes.Text_cell015_1.geometry} material={nodes.Text_cell015_1.material} />
          <mesh name="Text_cell015_2" geometry={nodes.Text_cell015_2.geometry} material={nodes.Text_cell015_2.material} />
        </group>
        <group name="Text_cell017" position={[1.107, 1.698, 0.153]}>
          <mesh name="Text_cell016_1" geometry={nodes.Text_cell016_1.geometry} material={nodes.Text_cell016_1.material} />
          <mesh name="Text_cell016_2" geometry={nodes.Text_cell016_2.geometry} material={nodes.Text_cell016_2.material} />
        </group>
        <group name="Text_cell018" position={[0.697, 1.98, 0.074]}>
          <mesh name="Text_cell017_1" geometry={nodes.Text_cell017_1.geometry} material={nodes.Text_cell017_1.material} />
          <mesh name="Text_cell017_2" geometry={nodes.Text_cell017_2.geometry} material={nodes.Text_cell017_2.material} />
        </group>
        <group name="Text_cell019" position={[1.145, 1.617, 0.153]}>
          <mesh name="Text_cell018_1" geometry={nodes.Text_cell018_1.geometry} material={nodes.Text_cell018_1.material} />
          <mesh name="Text_cell018_2" geometry={nodes.Text_cell018_2.geometry} material={nodes.Text_cell018_2.material} />
        </group>
        <group name="Text_cell020" position={[1.178, 1.822, 0.06]}>
          <mesh name="Text_cell019_1" geometry={nodes.Text_cell019_1.geometry} material={nodes.Text_cell019_1.material} />
          <mesh name="Text_cell019_2" geometry={nodes.Text_cell019_2.geometry} material={nodes.Text_cell019_2.material} />
        </group>
        <group name="Text_cell021" position={[0.933, 1.13, 0.117]}>
          <mesh name="Text_cell020_1" geometry={nodes.Text_cell020_1.geometry} material={nodes.Text_cell020_1.material} />
          <mesh name="Text_cell020_2" geometry={nodes.Text_cell020_2.geometry} material={nodes.Text_cell020_2.material} />
        </group>
        <group name="Text_cell022" position={[0.924, 1.824, 0.06]}>
          <mesh name="Text_cell021_1" geometry={nodes.Text_cell021_1.geometry} material={nodes.Text_cell021_1.material} />
          <mesh name="Text_cell021_2" geometry={nodes.Text_cell021_2.geometry} material={nodes.Text_cell021_2.material} />
        </group>
        <group name="Text_cell023" position={[0.986, 1.151, 0.128]}>
          <mesh name="Text_cell022_1" geometry={nodes.Text_cell022_1.geometry} material={nodes.Text_cell022_1.material} />
          <mesh name="Text_cell022_2" geometry={nodes.Text_cell022_2.geometry} material={nodes.Text_cell022_2.material} />
        </group>
        <group name="Text_cell024" position={[1.163, 1.503, 0.151]}>
          <mesh name="Text_cell023_1" geometry={nodes.Text_cell023_1.geometry} material={nodes.Text_cell023_1.material} />
          <mesh name="Text_cell023_2" geometry={nodes.Text_cell023_2.geometry} material={nodes.Text_cell023_2.material} />
        </group>
        <group name="Text_cell025" position={[1.119, 1.059, 0.024]}>
          <mesh name="Text_cell024_1" geometry={nodes.Text_cell024_1.geometry} material={nodes.Text_cell024_1.material} />
          <mesh name="Text_cell024_2" geometry={nodes.Text_cell024_2.geometry} material={nodes.Text_cell024_2.material} />
        </group>
        <group name="Text_cell026" position={[0.799, 0.961, 0.107]}>
          <mesh name="Text_cell025_1" geometry={nodes.Text_cell025_1.geometry} material={nodes.Text_cell025_1.material} />
          <mesh name="Text_cell025_2" geometry={nodes.Text_cell025_2.geometry} material={nodes.Text_cell025_2.material} />
        </group>
        <group name="Text_cell027" position={[1.137, 1.561, 0.038]}>
          <mesh name="Text_cell026_1" geometry={nodes.Text_cell026_1.geometry} material={nodes.Text_cell026_1.material} />
          <mesh name="Text_cell026_2" geometry={nodes.Text_cell026_2.geometry} material={nodes.Text_cell026_2.material} />
        </group>
        <group name="Text_cell028" position={[1.023, 1.767, 0.051]}>
          <mesh name="Text_cell027_1" geometry={nodes.Text_cell027_1.geometry} material={nodes.Text_cell027_1.material} />
          <mesh name="Text_cell027_2" geometry={nodes.Text_cell027_2.geometry} material={nodes.Text_cell027_2.material} />
        </group>
        <group name="Text_cell029" position={[1.119, 1.651, 0.051]}>
          <mesh name="Text_cell028_1" geometry={nodes.Text_cell028_1.geometry} material={nodes.Text_cell028_1.material} />
          <mesh name="Text_cell028_2" geometry={nodes.Text_cell028_2.geometry} material={nodes.Text_cell028_2.material} />
        </group>
        <group name="Text_cell030" position={[1.247, 1.713, 0.149]}>
          <mesh name="Text_cell029_1" geometry={nodes.Text_cell029_1.geometry} material={nodes.Text_cell029_1.material} />
          <mesh name="Text_cell029_2" geometry={nodes.Text_cell029_2.geometry} material={nodes.Text_cell029_2.material} />
        </group>
        <group name="Text_cell031" position={[0.89, 0.97, 0.105]}>
          <mesh name="Text_cell030_1" geometry={nodes.Text_cell030_1.geometry} material={nodes.Text_cell030_1.material} />
          <mesh name="Text_cell030_2" geometry={nodes.Text_cell030_2.geometry} material={nodes.Text_cell030_2.material} />
        </group>
        <group name="Text_cell032" position={[0.805, 1.09, 0.116]}>
          <mesh name="Text_cell031_1" geometry={nodes.Text_cell031_1.geometry} material={nodes.Text_cell031_1.material} />
          <mesh name="Text_cell031_2" geometry={nodes.Text_cell031_2.geometry} material={nodes.Text_cell031_2.material} />
        </group>
        <group name="Text_cell033" position={[0.384, 1.784, 0.112]}>
          <mesh name="Text_cell032_1" geometry={nodes.Text_cell032_1.geometry} material={nodes.Text_cell032_1.material} />
          <mesh name="Text_cell032_2" geometry={nodes.Text_cell032_2.geometry} material={nodes.Text_cell032_2.material} />
        </group>
        <group name="Text_cell034" position={[0.784, 1.111, 0.022]}>
          <mesh name="Text_cell033_1" geometry={nodes.Text_cell033_1.geometry} material={nodes.Text_cell033_1.material} />
          <mesh name="Text_cell033_2" geometry={nodes.Text_cell033_2.geometry} material={nodes.Text_cell033_2.material} />
        </group>
        <group name="Text_cell035" position={[0.3, 0.241, -0.029]}>
          <mesh name="Text_cell034_1" geometry={nodes.Text_cell034_1.geometry} material={nodes.Text_cell034_1.material} />
          <mesh name="Text_cell034_2" geometry={nodes.Text_cell034_2.geometry} material={nodes.Text_cell034_2.material} />
        </group>
        <group name="Text_cell036" position={[1.143, 1.612, 0.039]}>
          <mesh name="Text_cell035_1" geometry={nodes.Text_cell035_1.geometry} material={nodes.Text_cell035_1.material} />
          <mesh name="Text_cell035_2" geometry={nodes.Text_cell035_2.geometry} material={nodes.Text_cell035_2.material} />
        </group>
        <group name="Text_cell037" position={[0.877, 1.827, 0.16]}>
          <mesh name="Text_cell036_1" geometry={nodes.Text_cell036_1.geometry} material={nodes.Text_cell036_1.material} />
          <mesh name="Text_cell036_2" geometry={nodes.Text_cell036_2.geometry} material={nodes.Text_cell036_2.material} />
        </group>
        <group name="Text_cell038" position={[1.143, 1.554, 0.15]}>
          <mesh name="Text_cell037_1" geometry={nodes.Text_cell037_1.geometry} material={nodes.Text_cell037_1.material} />
          <mesh name="Text_cell037_2" geometry={nodes.Text_cell037_2.geometry} material={nodes.Text_cell037_2.material} />
        </group>
        <group name="Text_cell039" position={[1.043, 1.76, 0.158]}>
          <mesh name="Text_cell038_1" geometry={nodes.Text_cell038_1.geometry} material={nodes.Text_cell038_1.material} />
          <mesh name="Text_cell038_2" geometry={nodes.Text_cell038_2.geometry} material={nodes.Text_cell038_2.material} />
        </group>
        <group name="Text_cell040" position={[1.133, 1.324, 0.046]}>
          <mesh name="Text_cell039_1" geometry={nodes.Text_cell039_1.geometry} material={nodes.Text_cell039_1.material} />
          <mesh name="Text_cell039_2" geometry={nodes.Text_cell039_2.geometry} material={nodes.Text_cell039_2.material} />
        </group>
        <group name="Text_cell041" position={[1.314, 1.33, 0.116]}>
          <mesh name="Text_cell040_1" geometry={nodes.Text_cell040_1.geometry} material={nodes.Text_cell040_1.material} />
          <mesh name="Text_cell040_2" geometry={nodes.Text_cell040_2.geometry} material={nodes.Text_cell040_2.material} />
        </group>
        <group name="Text_cell042" position={[0.377, 1.172, 0.093]}>
          <mesh name="Text_cell041_1" geometry={nodes.Text_cell041_1.geometry} material={nodes.Text_cell041_1.material} />
          <mesh name="Text_cell041_2" geometry={nodes.Text_cell041_2.geometry} material={nodes.Text_cell041_2.material} />
        </group>
        <group name="Text_cell043" position={[1.118, 1.273, 0.135]}>
          <mesh name="Text_cell042_1" geometry={nodes.Text_cell042_1.geometry} material={nodes.Text_cell042_1.material} />
          <mesh name="Text_cell042_2" geometry={nodes.Text_cell042_2.geometry} material={nodes.Text_cell042_2.material} />
        </group>
        <group name="Text_cell044" position={[1.074, 1.216, 0.131]}>
          <mesh name="Text_cell043_1" geometry={nodes.Text_cell043_1.geometry} material={nodes.Text_cell043_1.material} />
          <mesh name="Text_cell043_2" geometry={nodes.Text_cell043_2.geometry} material={nodes.Text_cell043_2.material} />
        </group>
        <group name="Text_cell045" position={[1.312, 1.461, 0.146]}>
          <mesh name="Text_cell044_1" geometry={nodes.Text_cell044_1.geometry} material={nodes.Text_cell044_1.material} />
          <mesh name="Text_cell044_2" geometry={nodes.Text_cell044_2.geometry} material={nodes.Text_cell044_2.material} />
        </group>
        <group name="Text_cell046" position={[0.605, 1.99, 0.175]}>
          <mesh name="Text_cell045_1" geometry={nodes.Text_cell045_1.geometry} material={nodes.Text_cell045_1.material} />
          <mesh name="Text_cell045_2" geometry={nodes.Text_cell045_2.geometry} material={nodes.Text_cell045_2.material} />
        </group>
        <group name="Text_cell047" position={[0.959, 1.149, 0.02]}>
          <mesh name="Text_cell046_1" geometry={nodes.Text_cell046_1.geometry} material={nodes.Text_cell046_1.material} />
          <mesh name="Text_cell046_2" geometry={nodes.Text_cell046_2.geometry} material={nodes.Text_cell046_2.material} />
        </group>
        <group name="Text_cell048" position={[1.158, 1.082, 0.114]}>
          <mesh name="Text_cell047_1" geometry={nodes.Text_cell047_1.geometry} material={nodes.Text_cell047_1.material} />
          <mesh name="Text_cell047_2" geometry={nodes.Text_cell047_2.geometry} material={nodes.Text_cell047_2.material} />
        </group>
        <group name="Text_cell049" position={[0.98, 1.933, 0.071]}>
          <mesh name="Text_cell048_1" geometry={nodes.Text_cell048_1.geometry} material={nodes.Text_cell048_1.material} />
          <mesh name="Text_cell048_2" geometry={nodes.Text_cell048_2.geometry} material={nodes.Text_cell048_2.material} />
        </group>
        <group name="Text_cell050" position={[1.036, 1.185, 0.018]}>
          <mesh name="Text_cell049_1" geometry={nodes.Text_cell049_1.geometry} material={nodes.Text_cell049_1.material} />
          <mesh name="Text_cell049_2" geometry={nodes.Text_cell049_2.geometry} material={nodes.Text_cell049_2.material} />
        </group>
        <group name="Text_cell051" position={[1.147, 1.384, 0.137]}>
          <mesh name="Text_cell050_1" geometry={nodes.Text_cell050_1.geometry} material={nodes.Text_cell050_1.material} />
          <mesh name="Text_cell050_2" geometry={nodes.Text_cell050_2.geometry} material={nodes.Text_cell050_2.material} />
        </group>
        <group name="Text_cell052" position={[1.128, 1.861, 0.059]}>
          <mesh name="Text_cell051_1" geometry={nodes.Text_cell051_1.geometry} material={nodes.Text_cell051_1.material} />
          <mesh name="Text_cell051_2" geometry={nodes.Text_cell051_2.geometry} material={nodes.Text_cell051_2.material} />
        </group>
        <group name="Text_cell053" position={[1.061, 1.018, 0.015]}>
          <mesh name="Text_cell052_1" geometry={nodes.Text_cell052_1.geometry} material={nodes.Text_cell052_1.material} />
          <mesh name="Text_cell052_2" geometry={nodes.Text_cell052_2.geometry} material={nodes.Text_cell052_2.material} />
        </group>
        <group name="Text_cell054" position={[0.634, 0.957, 0.012]}>
          <mesh name="Text_cell053_1" geometry={nodes.Text_cell053_1.geometry} material={nodes.Text_cell053_1.material} />
          <mesh name="Text_cell053_2" geometry={nodes.Text_cell053_2.geometry} material={nodes.Text_cell053_2.material} />
        </group>
        <group name="Text_cell055" position={[1.249, 1.198, 0.124]}>
          <mesh name="Text_cell054_1" geometry={nodes.Text_cell054_1.geometry} material={nodes.Text_cell054_1.material} />
          <mesh name="Text_cell054_2" geometry={nodes.Text_cell054_2.geometry} material={nodes.Text_cell054_2.material} />
        </group>
        <group name="Text_cell056" position={[1.169, 1.508, 0.035]}>
          <mesh name="Text_cell055_1" geometry={nodes.Text_cell055_1.geometry} material={nodes.Text_cell055_1.material} />
          <mesh name="Text_cell055_2" geometry={nodes.Text_cell055_2.geometry} material={nodes.Text_cell055_2.material} />
        </group>
        <group name="Text_cell057" position={[0.675, 1.088, 0.116]}>
          <mesh name="Text_cell056_1" geometry={nodes.Text_cell056_1.geometry} material={nodes.Text_cell056_1.material} />
          <mesh name="Text_cell056_2" geometry={nodes.Text_cell056_2.geometry} material={nodes.Text_cell056_2.material} />
        </group>
        <group name="Text_cell058" position={[1.094, 1.695, 0.046]}>
          <mesh name="Text_cell057_1" geometry={nodes.Text_cell057_1.geometry} material={nodes.Text_cell057_1.material} />
          <mesh name="Text_cell057_2" geometry={nodes.Text_cell057_2.geometry} material={nodes.Text_cell057_2.material} />
        </group>
        <group name="Text_cell059" position={[0.354, 0.754, -0.004]}>
          <mesh name="Text_cell058_1" geometry={nodes.Text_cell058_1.geometry} material={nodes.Text_cell058_1.material} />
          <mesh name="Text_cell058_2" geometry={nodes.Text_cell058_2.geometry} material={nodes.Text_cell058_2.material} />
        </group>
        <group name="Text_cell060" position={[0.97, 1.814, 0.16]}>
          <mesh name="Text_cell059_1" geometry={nodes.Text_cell059_1.geometry} material={nodes.Text_cell059_1.material} />
          <mesh name="Text_cell059_2" geometry={nodes.Text_cell059_2.geometry} material={nodes.Text_cell059_2.material} />
        </group>
        <group name="Text_cell061" position={[1.266, 1.259, 0.133]}>
          <mesh name="Text_cell060_1" geometry={nodes.Text_cell060_1.geometry} material={nodes.Text_cell060_1.material} />
          <mesh name="Text_cell060_2" geometry={nodes.Text_cell060_2.geometry} material={nodes.Text_cell060_2.material} />
        </group>
        <group name="Text_cell062" position={[0.8, 0.965, 0.012]}>
          <mesh name="Text_cell061_1" geometry={nodes.Text_cell061_1.geometry} material={nodes.Text_cell061_1.material} />
          <mesh name="Text_cell061_2" geometry={nodes.Text_cell061_2.geometry} material={nodes.Text_cell061_2.material} />
        </group>
        <group name="Text_cell063" position={[1.039, 1.167, 0.129]}>
          <mesh name="Text_cell062_1" geometry={nodes.Text_cell062_1.geometry} material={nodes.Text_cell062_1.material} />
          <mesh name="Text_cell062_2" geometry={nodes.Text_cell062_2.geometry} material={nodes.Text_cell062_2.material} />
        </group>
        <group name="Text_cell064" position={[1.066, 1.896, 0.057]}>
          <mesh name="Text_cell063_1" geometry={nodes.Text_cell063_1.geometry} material={nodes.Text_cell063_1.material} />
          <mesh name="Text_cell063_2" geometry={nodes.Text_cell063_2.geometry} material={nodes.Text_cell063_2.material} />
        </group>
        <group name="Text_cell065" position={[0.626, 0.95, 0.115]}>
          <mesh name="Text_cell064_1" geometry={nodes.Text_cell064_1.geometry} material={nodes.Text_cell064_1.material} />
          <mesh name="Text_cell064_2" geometry={nodes.Text_cell064_2.geometry} material={nodes.Text_cell064_2.material} />
        </group>
        <group name="Text_cell066" position={[0.978, 1.801, 0.05]}>
          <mesh name="Text_cell065_1" geometry={nodes.Text_cell065_1.geometry} material={nodes.Text_cell065_1.material} />
          <mesh name="Text_cell065_2" geometry={nodes.Text_cell065_2.geometry} material={nodes.Text_cell065_2.material} />
        </group>
        <group name="Text_cell067" position={[0.18, 0.211, 0.021]}>
          <mesh name="Text_cell066_1" geometry={nodes.Text_cell066_1.geometry} material={nodes.Text_cell066_1.material} />
          <mesh name="Text_cell066_2" geometry={nodes.Text_cell066_2.geometry} material={nodes.Text_cell066_2.material} />
        </group>
        <group name="Text_cell068" position={[0.942, 1.942, 0.158]}>
          <mesh name="Text_cell067_1" geometry={nodes.Text_cell067_1.geometry} material={nodes.Text_cell067_1.material} />
          <mesh name="Text_cell067_2" geometry={nodes.Text_cell067_2.geometry} material={nodes.Text_cell067_2.material} />
        </group>
        <group name="Text_cell069" position={[1.294, 1.587, 0.04]}>
          <mesh name="Text_cell068_1" geometry={nodes.Text_cell068_1.geometry} material={nodes.Text_cell068_1.material} />
          <mesh name="Text_cell068_2" geometry={nodes.Text_cell068_2.geometry} material={nodes.Text_cell068_2.material} />
        </group>
        <group name="Text_cell070" position={[1.162, 1.398, 0.035]}>
          <mesh name="Text_cell069_1" geometry={nodes.Text_cell069_1.geometry} material={nodes.Text_cell069_1.material} />
          <mesh name="Text_cell069_2" geometry={nodes.Text_cell069_2.geometry} material={nodes.Text_cell069_2.material} />
        </group>
        <group name="Text_cell071" position={[1.186, 1.812, 0.153]}>
          <mesh name="Text_cell070_1" geometry={nodes.Text_cell070_1.geometry} material={nodes.Text_cell070_1.material} />
          <mesh name="Text_cell070_2" geometry={nodes.Text_cell070_2.geometry} material={nodes.Text_cell070_2.material} />
        </group>
        <group name="Text_cell072" position={[0.795, 1.843, 0.151]}>
          <mesh name="Text_cell071_1" geometry={nodes.Text_cell071_1.geometry} material={nodes.Text_cell071_1.material} />
          <mesh name="Text_cell071_2" geometry={nodes.Text_cell071_2.geometry} material={nodes.Text_cell071_2.material} />
        </group>
        <group name="Text_cell073" position={[0.839, 1.965, 0.172]}>
          <mesh name="Text_cell072_1" geometry={nodes.Text_cell072_1.geometry} material={nodes.Text_cell072_1.material} />
          <mesh name="Text_cell072_2" geometry={nodes.Text_cell072_2.geometry} material={nodes.Text_cell072_2.material} />
        </group>
        <group name="Text_cell074" position={[0.806, 1.834, 0.059]}>
          <mesh name="Text_cell073_1" geometry={nodes.Text_cell073_1.geometry} material={nodes.Text_cell073_1.material} />
          <mesh name="Text_cell073_2" geometry={nodes.Text_cell073_2.geometry} material={nodes.Text_cell073_2.material} />
        </group>
        <group name="Text_cell075" position={[0.972, 0.999, 0.018]}>
          <mesh name="Text_cell074_1" geometry={nodes.Text_cell074_1.geometry} material={nodes.Text_cell074_1.material} />
          <mesh name="Text_cell074_2" geometry={nodes.Text_cell074_2.geometry} material={nodes.Text_cell074_2.material} />
        </group>
        <group name="Text_cell076" position={[0.638, 1.08, 0.008]}>
          <mesh name="Text_cell075_1" geometry={nodes.Text_cell075_1.geometry} material={nodes.Text_cell075_1.material} />
          <mesh name="Text_cell075_2" geometry={nodes.Text_cell075_2.geometry} material={nodes.Text_cell075_2.material} />
        </group>
        <group name="Text_cell077" position={[1.263, 1.702, 0.05]}>
          <mesh name="Text_cell076_1" geometry={nodes.Text_cell076_1.geometry} material={nodes.Text_cell076_1.material} />
          <mesh name="Text_cell076_2" geometry={nodes.Text_cell076_2.geometry} material={nodes.Text_cell076_2.material} />
        </group>
        <group name="Text_cell078" position={[0.218, 1.935, 0.129]}>
          <mesh name="Text_cell077_1" geometry={nodes.Text_cell077_1.geometry} material={nodes.Text_cell077_1.material} />
          <mesh name="Text_cell077_2" geometry={nodes.Text_cell077_2.geometry} material={nodes.Text_cell077_2.material} />
        </group>
        <group name="Text_cell079" position={[1.066, 1.227, 0.028]}>
          <mesh name="Text_cell078_1" geometry={nodes.Text_cell078_1.geometry} material={nodes.Text_cell078_1.material} />
          <mesh name="Text_cell078_2" geometry={nodes.Text_cell078_2.geometry} material={nodes.Text_cell078_2.material} />
        </group>
        <group name="Text_cell080" position={[1.215, 1.152, 0.112]}>
          <mesh name="Text_cell079_1" geometry={nodes.Text_cell079_1.geometry} material={nodes.Text_cell079_1.material} />
          <mesh name="Text_cell079_2" geometry={nodes.Text_cell079_2.geometry} material={nodes.Text_cell079_2.material} />
        </group>
        <group name="Text_cell081" position={[0.669, 1.841, 0.122]}>
          <mesh name="Text_cell080_1" geometry={nodes.Text_cell080_1.geometry} material={nodes.Text_cell080_1.material} />
          <mesh name="Text_cell080_2" geometry={nodes.Text_cell080_2.geometry} material={nodes.Text_cell080_2.material} />
        </group>
        <group name="Text001_cell" position={[-0.966, 0.966, 0.108]}>
          <mesh name="Text001_cell081" geometry={nodes.Text001_cell081.geometry} material={nodes.Text001_cell081.material} />
          <mesh name="Text001_cell081_1" geometry={nodes.Text001_cell081_1.geometry} material={nodes.Text001_cell081_1.material} />
        </group>
        <group name="Text001_cell001" position={[-1.161, 1.855, 0.062]}>
          <mesh name="Text001_cell082" geometry={nodes.Text001_cell082.geometry} material={nodes.Text001_cell082.material} />
          <mesh name="Text001_cell082_1" geometry={nodes.Text001_cell082_1.geometry} material={nodes.Text001_cell082_1.material} />
        </group>
        <group name="Text001_cell002" position={[-0.883, 1.978, 0.17]}>
          <mesh name="Text001_cell001_1" geometry={nodes.Text001_cell001_1.geometry} material={nodes.Text001_cell001_1.material} />
          <mesh name="Text001_cell001_2" geometry={nodes.Text001_cell001_2.geometry} material={nodes.Text001_cell001_2.material} />
        </group>
        <group name="Text001_cell003" position={[-1.201, 1.53, 0.039]}>
          <mesh name="Text001_cell002_1" geometry={nodes.Text001_cell002_1.geometry} material={nodes.Text001_cell002_1.material} />
          <mesh name="Text001_cell002_2" geometry={nodes.Text001_cell002_2.geometry} material={nodes.Text001_cell002_2.material} />
        </group>
        <group name="Text001_cell004" position={[-1.367, 1.421, 0.146]}>
          <mesh name="Text001_cell003_1" geometry={nodes.Text001_cell003_1.geometry} material={nodes.Text001_cell003_1.material} />
          <mesh name="Text001_cell003_2" geometry={nodes.Text001_cell003_2.geometry} material={nodes.Text001_cell003_2.material} />
        </group>
        <group name="Text001_cell005" position={[-1.175, 1.307, 0.033]}>
          <mesh name="Text001_cell004_1" geometry={nodes.Text001_cell004_1.geometry} material={nodes.Text001_cell004_1.material} />
          <mesh name="Text001_cell004_2" geometry={nodes.Text001_cell004_2.geometry} material={nodes.Text001_cell004_2.material} />
        </group>
        <group name="Text001_cell006" position={[-0.698, 0.959, 0.03]}>
          <mesh name="Text001_cell005_1" geometry={nodes.Text001_cell005_1.geometry} material={nodes.Text001_cell005_1.material} />
          <mesh name="Text001_cell005_2" geometry={nodes.Text001_cell005_2.geometry} material={nodes.Text001_cell005_2.material} />
        </group>
        <group name="Text001_cell007" position={[-0.903, 1.978, 0.063]}>
          <mesh name="Text001_cell006_1" geometry={nodes.Text001_cell006_1.geometry} material={nodes.Text001_cell006_1.material} />
          <mesh name="Text001_cell006_2" geometry={nodes.Text001_cell006_2.geometry} material={nodes.Text001_cell006_2.material} />
        </group>
        <group name="Text001_cell008" position={[-0.927, 0.973, 0.022]}>
          <mesh name="Text001_cell007_1" geometry={nodes.Text001_cell007_1.geometry} material={nodes.Text001_cell007_1.material} />
          <mesh name="Text001_cell007_2" geometry={nodes.Text001_cell007_2.geometry} material={nodes.Text001_cell007_2.material} />
        </group>
        <group name="Text001_cell009" position={[-0.816, 1.828, 0.161]}>
          <mesh name="Text001_cell008_1" geometry={nodes.Text001_cell008_1.geometry} material={nodes.Text001_cell008_1.material} />
          <mesh name="Text001_cell008_2" geometry={nodes.Text001_cell008_2.geometry} material={nodes.Text001_cell008_2.material} />
        </group>
        <group name="Text001_cell010" position={[-1.213, 1.418, 0.039]}>
          <mesh name="Text001_cell009_1" geometry={nodes.Text001_cell009_1.geometry} material={nodes.Text001_cell009_1.material} />
          <mesh name="Text001_cell009_2" geometry={nodes.Text001_cell009_2.geometry} material={nodes.Text001_cell009_2.material} />
        </group>
        <group name="Text001_cell011" position={[-1.166, 1.874, 0.159]}>
          <mesh name="Text001_cell010_1" geometry={nodes.Text001_cell010_1.geometry} material={nodes.Text001_cell010_1.material} />
          <mesh name="Text001_cell010_2" geometry={nodes.Text001_cell010_2.geometry} material={nodes.Text001_cell010_2.material} />
        </group>
        <group name="Text001_cell012" position={[-0.413, 1.2, 0.121]}>
          <mesh name="Text001_cell011_1" geometry={nodes.Text001_cell011_1.geometry} material={nodes.Text001_cell011_1.material} />
          <mesh name="Text001_cell011_2" geometry={nodes.Text001_cell011_2.geometry} material={nodes.Text001_cell011_2.material} />
        </group>
        <group name="Text001_cell013" position={[-1.079, 1.775, 0.148]}>
          <mesh name="Text001_cell012_1" geometry={nodes.Text001_cell012_1.geometry} material={nodes.Text001_cell012_1.material} />
          <mesh name="Text001_cell012_2" geometry={nodes.Text001_cell012_2.geometry} material={nodes.Text001_cell012_2.material} />
        </group>
        <group name="Text001_cell014" position={[-1.191, 1.554, 0.147]}>
          <mesh name="Text001_cell013_1" geometry={nodes.Text001_cell013_1.geometry} material={nodes.Text001_cell013_1.material} />
          <mesh name="Text001_cell013_2" geometry={nodes.Text001_cell013_2.geometry} material={nodes.Text001_cell013_2.material} />
        </group>
        <group name="Text001_cell015" position={[-1.308, 1.704, 0.057]}>
          <mesh name="Text001_cell014_1" geometry={nodes.Text001_cell014_1.geometry} material={nodes.Text001_cell014_1.material} />
          <mesh name="Text001_cell014_2" geometry={nodes.Text001_cell014_2.geometry} material={nodes.Text001_cell014_2.material} />
        </group>
        <group name="Text001_cell016" position={[-1.09, 1.024, 0.112]}>
          <mesh name="Text001_cell015_1" geometry={nodes.Text001_cell015_1.geometry} material={nodes.Text001_cell015_1.material} />
          <mesh name="Text001_cell015_2" geometry={nodes.Text001_cell015_2.geometry} material={nodes.Text001_cell015_2.material} />
        </group>
        <group name="Text001_cell017" position={[-1.2, 1.604, 0.05]}>
          <mesh name="Text001_cell016_1" geometry={nodes.Text001_cell016_1.geometry} material={nodes.Text001_cell016_1.material} />
          <mesh name="Text001_cell016_2" geometry={nodes.Text001_cell016_2.geometry} material={nodes.Text001_cell016_2.material} />
        </group>
        <group name="Text001_cell018" position={[-1.153, 1.247, 0.134]}>
          <mesh name="Text001_cell017_1" geometry={nodes.Text001_cell017_1.geometry} material={nodes.Text001_cell017_1.material} />
          <mesh name="Text001_cell017_2" geometry={nodes.Text001_cell017_2.geometry} material={nodes.Text001_cell017_2.material} />
        </group>
        <group name="Text001_cell019" position={[-0.709, 1.832, 0.079]}>
          <mesh name="Text001_cell018_1" geometry={nodes.Text001_cell018_1.geometry} material={nodes.Text001_cell018_1.material} />
          <mesh name="Text001_cell018_2" geometry={nodes.Text001_cell018_2.geometry} material={nodes.Text001_cell018_2.material} />
        </group>
        <group name="Text001_cell020" position={[-1.074, 1.921, 0.161]}>
          <mesh name="Text001_cell019_1" geometry={nodes.Text001_cell019_1.geometry} material={nodes.Text001_cell019_1.material} />
          <mesh name="Text001_cell019_2" geometry={nodes.Text001_cell019_2.geometry} material={nodes.Text001_cell019_2.material} />
        </group>
        <group name="Text001_cell021" position={[-1.362, 1.374, 0.031]}>
          <mesh name="Text001_cell020_1" geometry={nodes.Text001_cell020_1.geometry} material={nodes.Text001_cell020_1.material} />
          <mesh name="Text001_cell020_2" geometry={nodes.Text001_cell020_2.geometry} material={nodes.Text001_cell020_2.material} />
        </group>
        <group name="Text001_cell022" position={[-0.727, 1.092, 0.029]}>
          <mesh name="Text001_cell021_1" geometry={nodes.Text001_cell021_1.geometry} material={nodes.Text001_cell021_1.material} />
          <mesh name="Text001_cell021_2" geometry={nodes.Text001_cell021_2.geometry} material={nodes.Text001_cell021_2.material} />
        </group>
        <group name="Text001_cell023" position={[-0.377, 0.291, 0.021]}>
          <mesh name="Text001_cell022_1" geometry={nodes.Text001_cell022_1.geometry} material={nodes.Text001_cell022_1.material} />
          <mesh name="Text001_cell022_2" geometry={nodes.Text001_cell022_2.geometry} material={nodes.Text001_cell022_2.material} />
        </group>
        <group name="Text001_cell024" position={[-1.125, 1.036, 0.017]}>
          <mesh name="Text001_cell023_1" geometry={nodes.Text001_cell023_1.geometry} material={nodes.Text001_cell023_1.material} />
          <mesh name="Text001_cell023_2" geometry={nodes.Text001_cell023_2.geometry} material={nodes.Text001_cell023_2.material} />
        </group>
        <group name="Text001_cell025" position={[-1.267, 1.153, 0.121]}>
          <mesh name="Text001_cell024_1" geometry={nodes.Text001_cell024_1.geometry} material={nodes.Text001_cell024_1.material} />
          <mesh name="Text001_cell024_2" geometry={nodes.Text001_cell024_2.geometry} material={nodes.Text001_cell024_2.material} />
        </group>
        <group name="Text001_cell026" position={[-1.131, 1.212, 0.024]}>
          <mesh name="Text001_cell025_1" geometry={nodes.Text001_cell025_1.geometry} material={nodes.Text001_cell025_1.material} />
          <mesh name="Text001_cell025_2" geometry={nodes.Text001_cell025_2.geometry} material={nodes.Text001_cell025_2.material} />
        </group>
        <group name="Text001_cell027" position={[-1.313, 1.255, 0.131]}>
          <mesh name="Text001_cell026_1" geometry={nodes.Text001_cell026_1.geometry} material={nodes.Text001_cell026_1.material} />
          <mesh name="Text001_cell026_2" geometry={nodes.Text001_cell026_2.geometry} material={nodes.Text001_cell026_2.material} />
        </group>
        <group name="Text001_cell028" position={[-0.829, 1.09, 0.125]}>
          <mesh name="Text001_cell027_1" geometry={nodes.Text001_cell027_1.geometry} material={nodes.Text001_cell027_1.material} />
          <mesh name="Text001_cell027_2" geometry={nodes.Text001_cell027_2.geometry} material={nodes.Text001_cell027_2.material} />
        </group>
        <group name="Text001_cell029" position={[-1.151, 1.638, 0.158]}>
          <mesh name="Text001_cell028_1" geometry={nodes.Text001_cell028_1.geometry} material={nodes.Text001_cell028_1.material} />
          <mesh name="Text001_cell028_2" geometry={nodes.Text001_cell028_2.geometry} material={nodes.Text001_cell028_2.material} />
        </group>
        <group name="Text001_cell030" position={[-1.026, 0.988, 0.028]}>
          <mesh name="Text001_cell029_1" geometry={nodes.Text001_cell029_1.geometry} material={nodes.Text001_cell029_1.material} />
          <mesh name="Text001_cell029_2" geometry={nodes.Text001_cell029_2.geometry} material={nodes.Text001_cell029_2.material} />
        </group>
        <group name="Text001_cell031" position={[-1.33, 1.279, 0.027]}>
          <mesh name="Text001_cell030_1" geometry={nodes.Text001_cell030_1.geometry} material={nodes.Text001_cell030_1.material} />
          <mesh name="Text001_cell030_2" geometry={nodes.Text001_cell030_2.geometry} material={nodes.Text001_cell030_2.material} />
        </group>
        <group name="Text001_cell032" position={[-0.235, 1.923, 0.17]}>
          <mesh name="Text001_cell031_1" geometry={nodes.Text001_cell031_1.geometry} material={nodes.Text001_cell031_1.material} />
          <mesh name="Text001_cell031_2" geometry={nodes.Text001_cell031_2.geometry} material={nodes.Text001_cell031_2.material} />
        </group>
        <group name="Text001_cell033" position={[-0.921, 1.854, 0.066]}>
          <mesh name="Text001_cell032_1" geometry={nodes.Text001_cell032_1.geometry} material={nodes.Text001_cell032_1.material} />
          <mesh name="Text001_cell032_2" geometry={nodes.Text001_cell032_2.geometry} material={nodes.Text001_cell032_2.material} />
        </group>
        <group name="Text001_cell034" position={[-1.337, 1.61, 0.047]}>
          <mesh name="Text001_cell033_1" geometry={nodes.Text001_cell033_1.geometry} material={nodes.Text001_cell033_1.material} />
          <mesh name="Text001_cell033_2" geometry={nodes.Text001_cell033_2.geometry} material={nodes.Text001_cell033_2.material} />
        </group>
        <group name="Text001_cell035" position={[-1.22, 1.459, 0.137]}>
          <mesh name="Text001_cell034_1" geometry={nodes.Text001_cell034_1.geometry} material={nodes.Text001_cell034_1.material} />
          <mesh name="Text001_cell034_2" geometry={nodes.Text001_cell034_2.geometry} material={nodes.Text001_cell034_2.material} />
        </group>
        <group name="Text001_cell036" position={[-1.202, 1.355, 0.034]}>
          <mesh name="Text001_cell035_1" geometry={nodes.Text001_cell035_1.geometry} material={nodes.Text001_cell035_1.material} />
          <mesh name="Text001_cell035_2" geometry={nodes.Text001_cell035_2.geometry} material={nodes.Text001_cell035_2.material} />
        </group>
        <group name="Text001_cell037" position={[-0.418, 1.198, 0.03]}>
          <mesh name="Text001_cell036_1" geometry={nodes.Text001_cell036_1.geometry} material={nodes.Text001_cell036_1.material} />
          <mesh name="Text001_cell036_2" geometry={nodes.Text001_cell036_2.geometry} material={nodes.Text001_cell036_2.material} />
        </group>
        <group name="Text001_cell038" position={[-0.392, 1.771, 0.115]}>
          <mesh name="Text001_cell037_1" geometry={nodes.Text001_cell037_1.geometry} material={nodes.Text001_cell037_1.material} />
          <mesh name="Text001_cell037_2" geometry={nodes.Text001_cell037_2.geometry} material={nodes.Text001_cell037_2.material} />
        </group>
        <group name="Text001_cell039" position={[-1.207, 1.507, 0.15]}>
          <mesh name="Text001_cell038_1" geometry={nodes.Text001_cell038_1.geometry} material={nodes.Text001_cell038_1.material} />
          <mesh name="Text001_cell038_2" geometry={nodes.Text001_cell038_2.geometry} material={nodes.Text001_cell038_2.material} />
        </group>
        <group name="Text001_cell040" position={[-1.215, 1.813, 0.162]}>
          <mesh name="Text001_cell039_1" geometry={nodes.Text001_cell039_1.geometry} material={nodes.Text001_cell039_1.material} />
          <mesh name="Text001_cell039_2" geometry={nodes.Text001_cell039_2.geometry} material={nodes.Text001_cell039_2.material} />
        </group>
        <group name="Text001_cell041" position={[-0.348, 0.721, 0.002]}>
          <mesh name="Text001_cell040_1" geometry={nodes.Text001_cell040_1.geometry} material={nodes.Text001_cell040_1.material} />
          <mesh name="Text001_cell040_2" geometry={nodes.Text001_cell040_2.geometry} material={nodes.Text001_cell040_2.material} />
        </group>
        <group name="Text001_cell042" position={[-1.2, 1.35, 0.137]}>
          <mesh name="Text001_cell041_1" geometry={nodes.Text001_cell041_1.geometry} material={nodes.Text001_cell041_1.material} />
          <mesh name="Text001_cell041_2" geometry={nodes.Text001_cell041_2.geometry} material={nodes.Text001_cell041_2.material} />
        </group>
        <group name="Text001_cell043" position={[-1.046, 1.804, 0.058]}>
          <mesh name="Text001_cell042_1" geometry={nodes.Text001_cell042_1.geometry} material={nodes.Text001_cell042_1.material} />
          <mesh name="Text001_cell042_2" geometry={nodes.Text001_cell042_2.geometry} material={nodes.Text001_cell042_2.material} />
        </group>
        <group name="Text001_cell044" position={[-0.965, 1.954, 0.158]}>
          <mesh name="Text001_cell043_1" geometry={nodes.Text001_cell043_1.geometry} material={nodes.Text001_cell043_1.material} />
          <mesh name="Text001_cell043_2" geometry={nodes.Text001_cell043_2.geometry} material={nodes.Text001_cell043_2.material} />
        </group>
        <group name="Text001_cell045" position={[-1.172, 1.599, 0.154]}>
          <mesh name="Text001_cell044_1" geometry={nodes.Text001_cell044_1.geometry} material={nodes.Text001_cell044_1.material} />
          <mesh name="Text001_cell044_2" geometry={nodes.Text001_cell044_2.geometry} material={nodes.Text001_cell044_2.material} />
        </group>
        <group name="Text001_cell046" position={[-1.201, 1.473, 0.034]}>
          <mesh name="Text001_cell045_1" geometry={nodes.Text001_cell045_1.geometry} material={nodes.Text001_cell045_1.material} />
          <mesh name="Text001_cell045_2" geometry={nodes.Text001_cell045_2.geometry} material={nodes.Text001_cell045_2.material} />
        </group>
        <group name="Text001_cell047" position={[-1.026, 1.943, 0.069]}>
          <mesh name="Text001_cell046_1" geometry={nodes.Text001_cell046_1.geometry} material={nodes.Text001_cell046_1.material} />
          <mesh name="Text001_cell046_2" geometry={nodes.Text001_cell046_2.geometry} material={nodes.Text001_cell046_2.material} />
        </group>
        <group name="Text001_cell048" position={[-0.975, 1.825, 0.163]}>
          <mesh name="Text001_cell047_1" geometry={nodes.Text001_cell047_1.geometry} material={nodes.Text001_cell047_1.material} />
          <mesh name="Text001_cell047_2" geometry={nodes.Text001_cell047_2.geometry} material={nodes.Text001_cell047_2.material} />
        </group>
        <group name="Text001_cell049" position={[-1.353, 1.56, 0.154]}>
          <mesh name="Text001_cell048_1" geometry={nodes.Text001_cell048_1.geometry} material={nodes.Text001_cell048_1.material} />
          <mesh name="Text001_cell048_2" geometry={nodes.Text001_cell048_2.geometry} material={nodes.Text001_cell048_2.material} />
        </group>
        <group name="Text001_cell050" position={[-0.896, 1.085, 0.118]}>
          <mesh name="Text001_cell049_1" geometry={nodes.Text001_cell049_1.geometry} material={nodes.Text001_cell049_1.material} />
          <mesh name="Text001_cell049_2" geometry={nodes.Text001_cell049_2.geometry} material={nodes.Text001_cell049_2.material} />
        </group>
        <group name="Text001_cell051" position={[-1.12, 1.908, 0.074]}>
          <mesh name="Text001_cell050_1" geometry={nodes.Text001_cell050_1.geometry} material={nodes.Text001_cell050_1.material} />
          <mesh name="Text001_cell050_2" geometry={nodes.Text001_cell050_2.geometry} material={nodes.Text001_cell050_2.material} />
        </group>
        <group name="Text001_cell052" position={[-1.205, 1.092, 0.02]}>
          <mesh name="Text001_cell051_1" geometry={nodes.Text001_cell051_1.geometry} material={nodes.Text001_cell051_1.material} />
          <mesh name="Text001_cell051_2" geometry={nodes.Text001_cell051_2.geometry} material={nodes.Text001_cell051_2.material} />
        </group>
        <group name="Text001_cell053" position={[-1.139, 1.704, 0.153]}>
          <mesh name="Text001_cell052_1" geometry={nodes.Text001_cell052_1.geometry} material={nodes.Text001_cell052_1.material} />
          <mesh name="Text001_cell052_2" geometry={nodes.Text001_cell052_2.geometry} material={nodes.Text001_cell052_2.material} />
        </group>
        <group name="Text001_cell054" position={[-0.73, 1.968, 0.173]}>
          <mesh name="Text001_cell053_1" geometry={nodes.Text001_cell053_1.geometry} material={nodes.Text001_cell053_1.material} />
          <mesh name="Text001_cell053_2" geometry={nodes.Text001_cell053_2.geometry} material={nodes.Text001_cell053_2.material} />
        </group>
        <group name="Text001_cell055" position={[-1.285, 1.781, 0.166]}>
          <mesh name="Text001_cell054_1" geometry={nodes.Text001_cell054_1.geometry} material={nodes.Text001_cell054_1.material} />
          <mesh name="Text001_cell054_2" geometry={nodes.Text001_cell054_2.geometry} material={nodes.Text001_cell054_2.material} />
        </group>
        <group name="Text001_cell056" position={[-1.159, 1.663, 0.046]}>
          <mesh name="Text001_cell055_1" geometry={nodes.Text001_cell055_1.geometry} material={nodes.Text001_cell055_1.material} />
          <mesh name="Text001_cell055_2" geometry={nodes.Text001_cell055_2.geometry} material={nodes.Text001_cell055_2.material} />
        </group>
        <group name="Text001_cell057" position={[-1.26, 1.773, 0.054]}>
          <mesh name="Text001_cell056_1" geometry={nodes.Text001_cell056_1.geometry} material={nodes.Text001_cell056_1.material} />
          <mesh name="Text001_cell056_2" geometry={nodes.Text001_cell056_2.geometry} material={nodes.Text001_cell056_2.material} />
        </group>
        <group name="Text001_cell058" position={[-0.427, 0.754, 0.099]}>
          <mesh name="Text001_cell057_1" geometry={nodes.Text001_cell057_1.geometry} material={nodes.Text001_cell057_1.material} />
          <mesh name="Text001_cell057_2" geometry={nodes.Text001_cell057_2.geometry} material={nodes.Text001_cell057_2.material} />
        </group>
        <group name="Text001_cell059" position={[-1.144, 1.264, 0.025]}>
          <mesh name="Text001_cell058_1" geometry={nodes.Text001_cell058_1.geometry} material={nodes.Text001_cell058_1.material} />
          <mesh name="Text001_cell058_2" geometry={nodes.Text001_cell058_2.geometry} material={nodes.Text001_cell058_2.material} />
        </group>
        <group name="Text001_cell060" position={[-1.2, 1.099, 0.124]}>
          <mesh name="Text001_cell059_1" geometry={nodes.Text001_cell059_1.geometry} material={nodes.Text001_cell059_1.material} />
          <mesh name="Text001_cell059_2" geometry={nodes.Text001_cell059_2.geometry} material={nodes.Text001_cell059_2.material} />
        </group>
        <group name="Text001_cell061" position={[-0.854, 1.089, 0.023]}>
          <mesh name="Text001_cell060_1" geometry={nodes.Text001_cell060_1.geometry} material={nodes.Text001_cell060_1.material} />
          <mesh name="Text001_cell060_2" geometry={nodes.Text001_cell060_2.geometry} material={nodes.Text001_cell060_2.material} />
        </group>
        <group name="Text001_cell062" position={[-1.003, 1.131, 0.022]}>
          <mesh name="Text001_cell061_1" geometry={nodes.Text001_cell061_1.geometry} material={nodes.Text001_cell061_1.material} />
          <mesh name="Text001_cell061_2" geometry={nodes.Text001_cell061_2.geometry} material={nodes.Text001_cell061_2.material} />
        </group>
        <group name="Text001_cell063" position={[-1.087, 1.166, 0.126]}>
          <mesh name="Text001_cell062_1" geometry={nodes.Text001_cell062_1.geometry} material={nodes.Text001_cell062_1.material} />
          <mesh name="Text001_cell062_2" geometry={nodes.Text001_cell062_2.geometry} material={nodes.Text001_cell062_2.material} />
        </group>
        <group name="Text001_cell064" position={[-1.125, 1.742, 0.051]}>
          <mesh name="Text001_cell063_1" geometry={nodes.Text001_cell063_1.geometry} material={nodes.Text001_cell063_1.material} />
          <mesh name="Text001_cell063_2" geometry={nodes.Text001_cell063_2.geometry} material={nodes.Text001_cell063_2.material} />
        </group>
        <group name="Text001_cell065" position={[-1.08, 1.181, 0.015]}>
          <mesh name="Text001_cell064_1" geometry={nodes.Text001_cell064_1.geometry} material={nodes.Text001_cell064_1.material} />
          <mesh name="Text001_cell064_2" geometry={nodes.Text001_cell064_2.geometry} material={nodes.Text001_cell064_2.material} />
        </group>
        <group name="Text001_cell066" position={[-0.982, 1.108, 0.113]}>
          <mesh name="Text001_cell065_1" geometry={nodes.Text001_cell065_1.geometry} material={nodes.Text001_cell065_1.material} />
          <mesh name="Text001_cell065_2" geometry={nodes.Text001_cell065_2.geometry} material={nodes.Text001_cell065_2.material} />
        </group>
        <group name="Text001_cell067" position={[-0.699, 1.066, 0.125]}>
          <mesh name="Text001_cell066_1" geometry={nodes.Text001_cell066_1.geometry} material={nodes.Text001_cell066_1.material} />
          <mesh name="Text001_cell066_2" geometry={nodes.Text001_cell066_2.geometry} material={nodes.Text001_cell066_2.material} />
        </group>
        <group name="Text001_cell068" position={[-0.848, 1.852, 0.058]}>
          <mesh name="Text001_cell067_1" geometry={nodes.Text001_cell067_1.geometry} material={nodes.Text001_cell067_1.material} />
          <mesh name="Text001_cell067_2" geometry={nodes.Text001_cell067_2.geometry} material={nodes.Text001_cell067_2.material} />
        </group>
        <group name="Text001_cell069" position={[-1.342, 1.663, 0.149]}>
          <mesh name="Text001_cell068_1" geometry={nodes.Text001_cell068_1.geometry} material={nodes.Text001_cell068_1.material} />
          <mesh name="Text001_cell068_2" geometry={nodes.Text001_cell068_2.geometry} material={nodes.Text001_cell068_2.material} />
        </group>
        <group name="Text001_cell070" position={[-1.266, 1.166, 0.018]}>
          <mesh name="Text001_cell069_1" geometry={nodes.Text001_cell069_1.geometry} material={nodes.Text001_cell069_1.material} />
          <mesh name="Text001_cell069_2" geometry={nodes.Text001_cell069_2.geometry} material={nodes.Text001_cell069_2.material} />
        </group>
        <group name="Text001_cell071" position={[-0.804, 0.945, 0.111]}>
          <mesh name="Text001_cell070_1" geometry={nodes.Text001_cell070_1.geometry} material={nodes.Text001_cell070_1.material} />
          <mesh name="Text001_cell070_2" geometry={nodes.Text001_cell070_2.geometry} material={nodes.Text001_cell070_2.material} />
        </group>
        <group name="Text001_cell072" position={[-1.228, 1.829, 0.057]}>
          <mesh name="Text001_cell071_1" geometry={nodes.Text001_cell071_1.geometry} material={nodes.Text001_cell071_1.material} />
          <mesh name="Text001_cell071_2" geometry={nodes.Text001_cell071_2.geometry} material={nodes.Text001_cell071_2.material} />
        </group>
        <group name="Text001_cell073" position={[-0.691, 1.995, 0.057]}>
          <mesh name="Text001_cell072_1" geometry={nodes.Text001_cell072_1.geometry} material={nodes.Text001_cell072_1.material} />
          <mesh name="Text001_cell072_2" geometry={nodes.Text001_cell072_2.geometry} material={nodes.Text001_cell072_2.material} />
        </group>
        <group name="Text001_cell074" position={[-1.368, 1.462, 0.039]}>
          <mesh name="Text001_cell073_1" geometry={nodes.Text001_cell073_1.geometry} material={nodes.Text001_cell073_1.material} />
          <mesh name="Text001_cell073_2" geometry={nodes.Text001_cell073_2.geometry} material={nodes.Text001_cell073_2.material} />
        </group>
        <group name="Text001_cell075" position={[-0.967, 1.816, 0.07]}>
          <mesh name="Text001_cell074_1" geometry={nodes.Text001_cell074_1.geometry} material={nodes.Text001_cell074_1.material} />
          <mesh name="Text001_cell074_2" geometry={nodes.Text001_cell074_2.geometry} material={nodes.Text001_cell074_2.material} />
        </group>
        <group name="Text001_cell076" position={[-0.209, 0.318, 0.021]}>
          <mesh name="Text001_cell075_1" geometry={nodes.Text001_cell075_1.geometry} material={nodes.Text001_cell075_1.material} />
          <mesh name="Text001_cell075_2" geometry={nodes.Text001_cell075_2.geometry} material={nodes.Text001_cell075_2.material} />
        </group>
        <group name="Text001_cell077" position={[-1.314, 1.726, 0.169]}>
          <mesh name="Text001_cell076_1" geometry={nodes.Text001_cell076_1.geometry} material={nodes.Text001_cell076_1.material} />
          <mesh name="Text001_cell076_2" geometry={nodes.Text001_cell076_2.geometry} material={nodes.Text001_cell076_2.material} />
        </group>
        <group name="Text001_cell078" position={[-1.363, 1.526, 0.052]}>
          <mesh name="Text001_cell077_1" geometry={nodes.Text001_cell077_1.geometry} material={nodes.Text001_cell077_1.material} />
          <mesh name="Text001_cell077_2" geometry={nodes.Text001_cell077_2.geometry} material={nodes.Text001_cell077_2.material} />
        </group>
        <group name="Text001_cell079" position={[-1.358, 1.313, 0.132]}>
          <mesh name="Text001_cell078_1" geometry={nodes.Text001_cell078_1.geometry} material={nodes.Text001_cell078_1.material} />
          <mesh name="Text001_cell078_2" geometry={nodes.Text001_cell078_2.geometry} material={nodes.Text001_cell078_2.material} />
        </group>
        <group name="Text001_cell080" position={[-0.322, 1.967, 0.057]}>
          <mesh name="Text001_cell079_1" geometry={nodes.Text001_cell079_1.geometry} material={nodes.Text001_cell079_1.material} />
          <mesh name="Text001_cell079_2" geometry={nodes.Text001_cell079_2.geometry} material={nodes.Text001_cell079_2.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/logoPP.glb')
