/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 logoPP5.glb -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useExplode } from "hooks/useExplode";



export default function Model(props) {
  const { nodes, materials } = useGLTF('/logoPP5.glb')
  const group = useRef();

  useExplode(group, {
    distance: 6,
  });


  return (
    <group {...props} dispose={null} ref={group}>
      <mesh name="Text_cell" geometry={nodes.Text_cell.geometry} material={materials['Material.001']} position={[0.325, 1.193, 0.117]} />
      <mesh name="Text_cell001" geometry={nodes.Text_cell001.geometry} material={materials['Material.001']} position={[0.266, 0.067, 0.049]} />
      <mesh name="Text_cell002" geometry={nodes.Text_cell002.geometry} material={materials['Material.001']} position={[0.589, 1.052, 0.116]} />
      <mesh name="Text_cell003" geometry={nodes.Text_cell003.geometry} material={materials['Material.001']} position={[0.613, -0.2, 0.13]} />
      <mesh name="Text_cell004" geometry={nodes.Text_cell004.geometry} material={materials['Material.001']} position={[0.419, -0.747, 0.114]} />
      <mesh name="Text_cell005" geometry={nodes.Text_cell005.geometry} material={materials['Material.001']} position={[0.313, 0.166, 0.105]} />
      <mesh name="Text_cell006" geometry={nodes.Text_cell006.geometry} material={materials['Material.001']} position={[1.678, 0.432, -0.112]} />
      <mesh name="Text_cell007" geometry={nodes.Text_cell007.geometry} material={materials['Material.001']} position={[0.899, 1.037, 0.142]} />
      <mesh name="Text_cell008" geometry={nodes.Text_cell008.geometry} material={materials['Material.001']} position={[0.911, -0.253, 0.11]} />
      <mesh name="Text_cell009" geometry={nodes.Text_cell009.geometry} material={materials['Material.001']} position={[1.667, -0.091, -0.107]} />
      <mesh name="Text_cell010" geometry={nodes.Text_cell010.geometry} material={materials['Material.001']} position={[0.327, -1.379, 0.064]} />
      <mesh name="Text_cell011" geometry={nodes.Text_cell011.geometry} material={materials['Material.001']} position={[1.65, 0.87, -0.12]} />
      <mesh name="Text_cell012" geometry={nodes.Text_cell012.geometry} material={materials['Material.001']} position={[1.86, 0.055, -0.004]} />
      <mesh name="Text_cell013" geometry={nodes.Text_cell013.geometry} material={materials['Material.001']} position={[0.297, -1.272, -0.112]} />
      <mesh name="Text_cell014" geometry={nodes.Text_cell014.geometry} material={materials['Material.001']} position={[0.25, 0.373, -0.045]} />
      <mesh name="Text_cell015" geometry={nodes.Text_cell015.geometry} material={materials['Material.001']} position={[0.957, -0.147, -0.129]} />
      <mesh name="Text_cell016" geometry={nodes.Text_cell016.geometry} material={materials['Material.001']} position={[1.767, 0.23, 0.165]} />
      <mesh name="Text_cell017" geometry={nodes.Text_cell017.geometry} material={materials['Material.001']} position={[0.758, 0.201, 0.137]} />
      <mesh name="Text_cell018" geometry={nodes.Text_cell018.geometry} material={materials['Material.001']} position={[0.897, 0.231, -0.089]} />
      <mesh name="Text_cell019" geometry={nodes.Text_cell019.geometry} material={materials['Material.001']} position={[1.447, -0.179, -0.065]} />
      <mesh name="Text_cell020" geometry={nodes.Text_cell020.geometry} material={materials['Material.001']} position={[0.263, 0.682, -0.035]} />
      <mesh name="Text_cell021" geometry={nodes.Text_cell021.geometry} material={materials['Material.001']} position={[0.242, -0.14, -0.074]} />
      <mesh name="Text_cell022" geometry={nodes.Text_cell022.geometry} material={materials['Material.001']} position={[1.232, 0.931, 0.022]} />
      <mesh name="Text_cell023" geometry={nodes.Text_cell023.geometry} material={materials['Material.001']} position={[1.841, 1.118, 0.109]} />
      <mesh name="Text_cell024" geometry={nodes.Text_cell024.geometry} material={materials['Material.001']} position={[0.51, -1.082, -0.085]} />
      <mesh name="Text_cell025" geometry={nodes.Text_cell025.geometry} material={materials['Material.001']} position={[0.866, 1.083, -0.124]} />
      <mesh name="Text_cell026" geometry={nodes.Text_cell026.geometry} material={materials['Material.001']} position={[1.927, 0.918, 0.109]} />
      <mesh name="Text_cell027" geometry={nodes.Text_cell027.geometry} material={materials['Material.001']} position={[1.162, 0.978, -0.07]} />
      <mesh name="Text_cell028" geometry={nodes.Text_cell028.geometry} material={materials['Material.001']} position={[1.927, 1.009, -0.041]} />
      <mesh name="Text_cell029" geometry={nodes.Text_cell029.geometry} material={materials['Material.001']} position={[0.795, 0.808, 0.076]} />
      <mesh name="Text_cell030" geometry={nodes.Text_cell030.geometry} material={materials['Material.001']} position={[1.98, 0.401, 0.03]} />
      <mesh name="Text_cell031" geometry={nodes.Text_cell031.geometry} material={materials['Material.001']} position={[0.425, 0.374, -0.113]} />
      <mesh name="Text_cell032" geometry={nodes.Text_cell032.geometry} material={materials['Material.001']} position={[0.35, -1.166, 0.132]} />
      <mesh name="Text_cell033" geometry={nodes.Text_cell033.geometry} material={materials['Material.001']} position={[0.505, -1.35, -0.123]} />
      <mesh name="Text_cell034" geometry={nodes.Text_cell034.geometry} material={materials['Material.001']} position={[0.306, -0.661, -0.091]} />
      <mesh name="Text_cell035" geometry={nodes.Text_cell035.geometry} material={materials['Material.001']} position={[0.545, 0.298, 0.114]} />
      <mesh name="Text_cell036" geometry={nodes.Text_cell036.geometry} material={materials['Material.001']} position={[0.455, 0.609, -0.111]} />
      <mesh name="Text_cell037" geometry={nodes.Text_cell037.geometry} material={materials['Material.001']} position={[0.666, -0.938, 0.02]} />
      <mesh name="Text_cell038" geometry={nodes.Text_cell038.geometry} material={materials['Material.001']} position={[0.654, -1.384, 0.049]} />
      <mesh name="Text_cell039" geometry={nodes.Text_cell039.geometry} material={materials['Material.001']} position={[1.174, -0.205, 0.005]} />
      <mesh name="Text_cell040" geometry={nodes.Text_cell040.geometry} material={materials['Material.001']} position={[0.385, -0.118, -0.112]} />
      <mesh name="Text_cell041" geometry={nodes.Text_cell041.geometry} material={materials['Material.001']} position={[1.756, 1.23, -0.057]} />
      <mesh name="Text_cell042" geometry={nodes.Text_cell042.geometry} material={materials['Material.001']} position={[0.34, 1.405, 0.002]} />
      <mesh name="Text_cell043" geometry={nodes.Text_cell043.geometry} material={materials['Material.001']} position={[0.882, -0.044, 0.127]} />
      <mesh name="Text_cell044" geometry={nodes.Text_cell044.geometry} material={materials['Material.001']} position={[1.559, -0.107, 0.103]} />
      <mesh name="Text_cell045" geometry={nodes.Text_cell045.geometry} material={materials['Material.001']} position={[1.435, 1.326, 0.132]} />
      <mesh name="Text_cell046" geometry={nodes.Text_cell046.geometry} material={materials['Material.001']} position={[0.486, -0.843, -0.129]} />
      <mesh name="Text_cell047" geometry={nodes.Text_cell047.geometry} material={materials['Material.001']} position={[1.272, 1.203, -0.149]} />
      <mesh name="Text_cell048" geometry={nodes.Text_cell048.geometry} material={materials['Material.001']} position={[1.016, 1.027, -0.094]} />
      <mesh name="Text_cell049" geometry={nodes.Text_cell049.geometry} material={materials['Material.001']} position={[0.245, 0.805, 0.063]} />
      <mesh name="Text_cell050" geometry={nodes.Text_cell050.geometry} material={materials['Material.001']} position={[1.702, 1.058, 0.133]} />
      <mesh name="Text_cell051" geometry={nodes.Text_cell051.geometry} material={materials['Material.001']} position={[0.239, 1.324, -0.053]} />
      <mesh name="Text_cell052" geometry={nodes.Text_cell052.geometry} material={materials['Material.001']} position={[0.312, -0.083, 0.099]} />
      <mesh name="Text_cell053" geometry={nodes.Text_cell053.geometry} material={materials['Material.001']} position={[1.027, 1.348, -0.117]} />
      <mesh name="Text_cell054" geometry={nodes.Text_cell054.geometry} material={materials['Material.001']} position={[1.43, 1.368, -0.054]} />
      <mesh name="Text_cell055" geometry={nodes.Text_cell055.geometry} material={materials['Material.001']} position={[0.478, 0.555, 0.136]} />
      <mesh name="Text_cell056" geometry={nodes.Text_cell056.geometry} material={materials['Material.001']} position={[0.749, 0.396, 0.034]} />
      <mesh name="Text_cell057" geometry={nodes.Text_cell057.geometry} material={materials['Material.001']} position={[1.953, 0.754, 0.067]} />
      <mesh name="Text_cell058" geometry={nodes.Text_cell058.geometry} material={materials['Material.001']} position={[0.599, -1.261, 0.117]} />
      <mesh name="Text_cell059" geometry={nodes.Text_cell059.geometry} material={materials['Material.001']} position={[0.671, -0.127, -0.133]} />
      <mesh name="Text_cell060" geometry={nodes.Text_cell060.geometry} material={materials['Material.001']} position={[1.476, 0.712, -0.064]} />
      <mesh name="Text_cell061" geometry={nodes.Text_cell061.geometry} material={materials['Material.001']} position={[1.645, 1.153, -0.14]} />
      <mesh name="Text_cell062" geometry={nodes.Text_cell062.geometry} material={materials['Material.001']} position={[0.307, 0.404, 0.128]} />
      <mesh name="Text_cell063" geometry={nodes.Text_cell063.geometry} material={materials['Material.001']} position={[0.405, 1.287, -0.131]} />
      <mesh name="Text_cell064" geometry={nodes.Text_cell064.geometry} material={materials['Material.001']} position={[0.686, 0.553, -0.114]} />
      <mesh name="Text_cell065" geometry={nodes.Text_cell065.geometry} material={materials['Material.001']} position={[0.778, 1.392, 0.064]} />
      <mesh name="Text_cell066" geometry={nodes.Text_cell066.geometry} material={materials['Material.001']} position={[0.675, -1.358, -0.094]} />
      <mesh name="Text_cell067" geometry={nodes.Text_cell067.geometry} material={materials['Material.001']} position={[0.336, -0.355, 0.098]} />
      <mesh name="Text_cell068" geometry={nodes.Text_cell068.geometry} material={materials['Material.001']} position={[1.449, 0.084, -0.152]} />
      <mesh name="Text_cell069" geometry={nodes.Text_cell069.geometry} material={materials['Material.001']} position={[1.453, 0.969, -0.133]} />
      <mesh name="Text_cell070" geometry={nodes.Text_cell070.geometry} material={materials['Material.001']} position={[1.496, 0.76, 0.132]} />
      <mesh name="Text_cell071" geometry={nodes.Text_cell071.geometry} material={materials['Material.001']} position={[1.527, 0.837, -0.158]} />
      <mesh name="Text_cell072" geometry={nodes.Text_cell072.geometry} material={materials['Material.001']} position={[0.267, -0.974, -0.054]} />
      <mesh name="Text_cell073" geometry={nodes.Text_cell073.geometry} material={materials['Material.001']} position={[1.557, 0.274, 0.141]} />
      <mesh name="Text_cell074" geometry={nodes.Text_cell074.geometry} material={materials['Material.001']} position={[1.37, 0.297, 0.051]} />
      <mesh name="Text_cell075" geometry={nodes.Text_cell075.geometry} material={materials['Material.001']} position={[1.076, 1.304, 0.116]} />
      <mesh name="Text_cell076" geometry={nodes.Text_cell076.geometry} material={materials['Material.001']} position={[0.521, 0.898, -0.127]} />
      <mesh name="Text_cell077" geometry={nodes.Text_cell077.geometry} material={materials['Material.001']} position={[1.665, 1.27, 0.071]} />
      <mesh name="Text_cell078" geometry={nodes.Text_cell078.geometry} material={materials['Material.001']} position={[1.121, 0.179, -0.043]} />
      <mesh name="Text_cell079" geometry={nodes.Text_cell079.geometry} material={materials['Material.001']} position={[0.401, 0.795, 0.116]} />
      <mesh name="Text_cell080" geometry={nodes.Text_cell080.geometry} material={materials['Material.001']} position={[1.626, 0.041, -0.125]} />
      <mesh name="Text_cell081" geometry={nodes.Text_cell081.geometry} material={materials['Material.001']} position={[0.781, 1.203, 0.079]} />
      <mesh name="Text_cell082" geometry={nodes.Text_cell082.geometry} material={materials['Material.001']} position={[0.717, -1.089, -0.013]} />
      <mesh name="Text_cell083" geometry={nodes.Text_cell083.geometry} material={materials['Material.001']} position={[0.703, -0.594, 0.085]} />
      <mesh name="Text_cell084" geometry={nodes.Text_cell084.geometry} material={materials['Material.001']} position={[0.61, -0.675, -0.131]} />
      <mesh name="Text_cell085" geometry={nodes.Text_cell085.geometry} material={materials['Material.001']} position={[0.788, 0.931, -0.105]} />
      <mesh name="Text_cell086" geometry={nodes.Text_cell086.geometry} material={materials['Material.001']} position={[0.686, -1.182, -0.096]} />
      <mesh name="Text_cell087" geometry={nodes.Text_cell087.geometry} material={materials['Material.001']} position={[1.372, -0.087, -0.15]} />
      <mesh name="Text_cell088" geometry={nodes.Text_cell088.geometry} material={materials['Material.001']} position={[0.308, 1.057, -0.1]} />
      <mesh name="Text_cell089" geometry={nodes.Text_cell089.geometry} material={materials['Material.001']} position={[0.376, -0.334, -0.113]} />
      <mesh name="Text_cell090" geometry={nodes.Text_cell090.geometry} material={materials['Material.001']} position={[0.478, 1.352, 0.111]} />
      <mesh name="Text_cell091" geometry={nodes.Text_cell091.geometry} material={materials['Material.001']} position={[0.426, 0.085, -0.1]} />
      <mesh name="Text_cell092" geometry={nodes.Text_cell092.geometry} material={materials['Material.001']} position={[1.814, 0.745, -0.143]} />
      <mesh name="Text_cell093" geometry={nodes.Text_cell093.geometry} material={materials['Material.001']} position={[0.683, -0.41, -0.08]} />
      <mesh name="Text_cell094" geometry={nodes.Text_cell094.geometry} material={materials['Material.001']} position={[1.196, 0.015, 0.138]} />
      <mesh name="Text_cell095" geometry={nodes.Text_cell095.geometry} material={materials['Material.001']} position={[0.637, 1.277, -0.096]} />
      <mesh name="Text_cell096" geometry={nodes.Text_cell096.geometry} material={materials['Material.001']} position={[1.374, 0.114, 0.13]} />
      <mesh name="Text_cell097" geometry={nodes.Text_cell097.geometry} material={materials['Material.001']} position={[0.775, 0.194, -0.154]} />
      <mesh name="Text_cell098" geometry={nodes.Text_cell098.geometry} material={materials['Material.001']} position={[1.33, 1.093, 0.144]} />
      <mesh name="Text_cell099" geometry={nodes.Text_cell099.geometry} material={materials['Material.001']} position={[1.845, 0.155, -0.139]} />
      <mesh name="Text001_cell" geometry={nodes.Text001_cell.geometry} material={materials['Material.002']} position={[-1.28, 1.322, -0.137]} />
      <mesh name="Text001_cell001" geometry={nodes.Text001_cell001.geometry} material={materials['Material.002']} position={[-1.742, 0.063, -0.133]} />
      <mesh name="Text001_cell002" geometry={nodes.Text001_cell002.geometry} material={materials['Material.002']} position={[-0.495, -0.999, -0.073]} />
      <mesh name="Text001_cell003" geometry={nodes.Text001_cell003.geometry} material={materials['Material.002']} position={[-0.423, 1.16, 0.119]} />
      <mesh name="Text001_cell004" geometry={nodes.Text001_cell004.geometry} material={materials['Material.002']} position={[-0.457, -1.302, 0.13]} />
      <mesh name="Text001_cell005" geometry={nodes.Text001_cell005.geometry} material={materials['Material.002']} position={[-0.615, -0.364, 0.134]} />
      <mesh name="Text001_cell006" geometry={nodes.Text001_cell006.geometry} material={materials['Material.002']} position={[-0.772, -0.225, 0.137]} />
      <mesh name="Text001_cell007" geometry={nodes.Text001_cell007.geometry} material={materials['Material.002']} position={[-0.295, -1.214, 0.098]} />
      <mesh name="Text001_cell008" geometry={nodes.Text001_cell008.geometry} material={materials['Material.002']} position={[-1.346, 1.087, 0.147]} />
      <mesh name="Text001_cell009" geometry={nodes.Text001_cell009.geometry} material={materials['Material.002']} position={[-2.009, 0.576, 0.014]} />
      <mesh name="Text001_cell010" geometry={nodes.Text001_cell010.geometry} material={materials['Material.002']} position={[-1.287, 0.041, 0.124]} />
      <mesh name="Text001_cell011" geometry={nodes.Text001_cell011.geometry} material={materials['Material.002']} position={[-1.771, 0.441, -0.141]} />
      <mesh name="Text001_cell012" geometry={nodes.Text001_cell012.geometry} material={materials['Material.002']} position={[-0.399, -1.082, -0.098]} />
      <mesh name="Text001_cell013" geometry={nodes.Text001_cell013.geometry} material={materials['Material.002']} position={[-0.659, -0.445, -0.11]} />
      <mesh name="Text001_cell014" geometry={nodes.Text001_cell014.geometry} material={materials['Material.002']} position={[-1.207, -0.119, -0.106]} />
      <mesh name="Text001_cell015" geometry={nodes.Text001_cell015.geometry} material={materials['Material.002']} position={[-1.95, 0.179, -0.103]} />
      <mesh name="Text001_cell016" geometry={nodes.Text001_cell016.geometry} material={materials['Material.002']} position={[-0.379, -0.552, -0.109]} />
      <mesh name="Text001_cell017" geometry={nodes.Text001_cell017.geometry} material={materials['Material.002']} position={[-0.67, 0.926, 0.137]} />
      <mesh name="Text001_cell018" geometry={nodes.Text001_cell018.geometry} material={materials['Material.002']} position={[-0.484, 0.334, -0.141]} />
      <mesh name="Text001_cell019" geometry={nodes.Text001_cell019.geometry} material={materials['Material.002']} position={[-0.898, 1.204, -0.155]} />
      <mesh name="Text001_cell020" geometry={nodes.Text001_cell020.geometry} material={materials['Material.002']} position={[-1.097, -0.214, 0.103]} />
      <mesh name="Text001_cell021" geometry={nodes.Text001_cell021.geometry} material={materials['Material.002']} position={[-0.528, 1.298, -0.128]} />
      <mesh name="Text001_cell022" geometry={nodes.Text001_cell022.geometry} material={materials['Material.002']} position={[-0.393, -1.253, -0.144]} />
      <mesh name="Text001_cell023" geometry={nodes.Text001_cell023.geometry} material={materials['Material.002']} position={[-0.589, -0.765, 0.101]} />
      <mesh name="Text001_cell024" geometry={nodes.Text001_cell024.geometry} material={materials['Material.002']} position={[-1.129, 1.234, 0.142]} />
      <mesh name="Text001_cell025" geometry={nodes.Text001_cell025.geometry} material={materials['Material.002']} position={[-0.336, 0.167, 0.058]} />
      <mesh name="Text001_cell026" geometry={nodes.Text001_cell026.geometry} material={materials['Material.002']} position={[-1.835, 0.067, 0.073]} />
      <mesh name="Text001_cell027" geometry={nodes.Text001_cell027.geometry} material={materials['Material.002']} position={[-1.615, 0.422, 0.101]} />
      <mesh name="Text001_cell028" geometry={nodes.Text001_cell028.geometry} material={materials['Material.002']} position={[-1.022, -0.173, -0.105]} />
      <mesh name="Text001_cell029" geometry={nodes.Text001_cell029.geometry} material={materials['Material.002']} position={[-0.258, -0.289, 0.085]} />
      <mesh name="Text001_cell030" geometry={nodes.Text001_cell030.geometry} material={materials['Material.002']} position={[-0.272, 1.248, -0.043]} />
      <mesh name="Text001_cell031" geometry={nodes.Text001_cell031.geometry} material={materials['Material.002']} position={[-1.995, 0.273, 0.011]} />
      <mesh name="Text001_cell032" geometry={nodes.Text001_cell032.geometry} material={materials['Material.002']} position={[-0.93, 0.235, 0.025]} />
      <mesh name="Text001_cell033" geometry={nodes.Text001_cell033.geometry} material={materials['Material.002']} position={[-1.534, 1.332, -0.066]} />
      <mesh name="Text001_cell034" geometry={nodes.Text001_cell034.geometry} material={materials['Material.002']} position={[-1.374, -0.17, -0.13]} />
      <mesh name="Text001_cell035" geometry={nodes.Text001_cell035.geometry} material={materials['Material.002']} position={[-0.961, 0.139, -0.146]} />
      <mesh name="Text001_cell036" geometry={nodes.Text001_cell036.geometry} material={materials['Material.002']} position={[-1.537, -0.161, -0.024]} />
      <mesh name="Text001_cell037" geometry={nodes.Text001_cell037.geometry} material={materials['Material.002']} position={[-0.246, 0.654, 0.011]} />
      <mesh name="Text001_cell038" geometry={nodes.Text001_cell038.geometry} material={materials['Material.002']} position={[-0.475, 0.758, 0.119]} />
      <mesh name="Text001_cell039" geometry={nodes.Text001_cell039.geometry} material={materials['Material.002']} position={[-1.952, 0.917, 0.016]} />
      <mesh name="Text001_cell040" geometry={nodes.Text001_cell040.geometry} material={materials['Material.002']} position={[-0.415, -0.337, 0.092]} />
      <mesh name="Text001_cell041" geometry={nodes.Text001_cell041.geometry} material={materials['Material.002']} position={[-0.278, -0.437, -0.062]} />
      <mesh name="Text001_cell042" geometry={nodes.Text001_cell042.geometry} material={materials['Material.002']} position={[-0.567, 0.382, 0.133]} />
      <mesh name="Text001_cell043" geometry={nodes.Text001_cell043.geometry} material={materials['Material.002']} position={[-0.348, -0.756, -0.102]} />
      <mesh name="Text001_cell044" geometry={nodes.Text001_cell044.geometry} material={materials['Material.002']} position={[-0.692, -1.106, -0.003]} />
      <mesh name="Text001_cell045" geometry={nodes.Text001_cell045.geometry} material={materials['Material.002']} position={[-0.681, 1.138, 0.092]} />
      <mesh name="Text001_cell046" geometry={nodes.Text001_cell046.geometry} material={materials['Material.002']} position={[-0.677, -0.81, -0.082]} />
      <mesh name="Text001_cell047" geometry={nodes.Text001_cell047.geometry} material={materials['Material.002']} position={[-0.818, 0.846, 0.14]} />
      <mesh name="Text001_cell048" geometry={nodes.Text001_cell048.geometry} material={materials['Material.002']} position={[-1.335, -0.183, 0.115]} />
      <mesh name="Text001_cell049" geometry={nodes.Text001_cell049.geometry} material={materials['Material.002']} position={[-0.293, 0.961, 0.102]} />
      <mesh name="Text001_cell050" geometry={nodes.Text001_cell050.geometry} material={materials['Material.002']} position={[-0.352, 1.374, 0.088]} />
      <mesh name="Text001_cell051" geometry={nodes.Text001_cell051.geometry} material={materials['Material.002']} position={[-0.282, -0.694, 0.095]} />
      <mesh name="Text001_cell052" geometry={nodes.Text001_cell052.geometry} material={materials['Material.002']} position={[-1.532, 0.191, -0.145]} />
      <mesh name="Text001_cell053" geometry={nodes.Text001_cell053.geometry} material={materials['Material.002']} position={[-0.354, -0.528, 0.096]} />
      <mesh name="Text001_cell054" geometry={nodes.Text001_cell054.geometry} material={materials['Material.002']} position={[-0.513, 1.011, 0.108]} />
      <mesh name="Text001_cell055" geometry={nodes.Text001_cell055.geometry} material={materials['Material.002']} position={[-1.384, 0.835, -0.025]} />
      <mesh name="Text001_cell056" geometry={nodes.Text001_cell056.geometry} material={materials['Material.002']} position={[-0.684, 1.379, 0.027]} />
      <mesh name="Text001_cell057" geometry={nodes.Text001_cell057.geometry} material={materials['Material.002']} position={[-1.423, 1.114, -0.145]} />
      <mesh name="Text001_cell058" geometry={nodes.Text001_cell058.geometry} material={materials['Material.002']} position={[-0.409, -0.941, 0.116]} />
      <mesh name="Text001_cell059" geometry={nodes.Text001_cell059.geometry} material={materials['Material.002']} position={[-0.304, 0.382, 0.087]} />
      <mesh name="Text001_cell060" geometry={nodes.Text001_cell060.geometry} material={materials['Material.002']} position={[-1.714, 1.213, -0.007]} />
      <mesh name="Text001_cell061" geometry={nodes.Text001_cell061.geometry} material={materials['Material.002']} position={[-0.71, 0.48, 0.118]} />
      <mesh name="Text001_cell062" geometry={nodes.Text001_cell062.geometry} material={materials['Material.002']} position={[-0.649, -0.452, 0.129]} />
      <mesh name="Text001_cell063" geometry={nodes.Text001_cell063.geometry} material={materials['Material.002']} position={[-0.405, 0.925, -0.104]} />
      <mesh name="Text001_cell064" geometry={nodes.Text001_cell064.geometry} material={materials['Material.002']} position={[-0.72, 0.823, -0.129]} />
      <mesh name="Text001_cell065" geometry={nodes.Text001_cell065.geometry} material={materials['Material.002']} position={[-0.822, 1.353, 0.08]} />
      <mesh name="Text001_cell066" geometry={nodes.Text001_cell066.geometry} material={materials['Material.002']} position={[-0.581, -0.194, -0.131]} />
      <mesh name="Text001_cell067" geometry={nodes.Text001_cell067.geometry} material={materials['Material.002']} position={[-0.25, -1.063, -0.096]} />
      <mesh name="Text001_cell068" geometry={nodes.Text001_cell068.geometry} material={materials['Material.002']} position={[-0.991, 1.412, -0.057]} />
      <mesh name="Text001_cell069" geometry={nodes.Text001_cell069.geometry} material={materials['Material.002']} position={[-0.3, -0.998, 0.072]} />
      <mesh name="Text001_cell070" geometry={nodes.Text001_cell070.geometry} material={materials['Material.002']} position={[-0.273, -1.372, -0.052]} />
      <mesh name="Text001_cell071" geometry={nodes.Text001_cell071.geometry} material={materials['Material.002']} position={[-1.699, 1.028, 0.15]} />
      <mesh name="Text001_cell072" geometry={nodes.Text001_cell072.geometry} material={materials['Material.002']} position={[-1.398, 1.371, 0.042]} />
      <mesh name="Text001_cell073" geometry={nodes.Text001_cell073.geometry} material={materials['Material.002']} position={[-1.635, 0.755, 0.138]} />
      <mesh name="Text001_cell074" geometry={nodes.Text001_cell074.geometry} material={materials['Material.002']} position={[-1.917, 0.803, -0.147]} />
      <mesh name="Text001_cell075" geometry={nodes.Text001_cell075.geometry} material={materials['Material.002']} position={[-0.738, -0.556, 0.086]} />
      <mesh name="Text001_cell076" geometry={nodes.Text001_cell076.geometry} material={materials['Material.002']} position={[-0.887, 1.073, 0.143]} />
      <mesh name="Text001_cell077" geometry={nodes.Text001_cell077.geometry} material={materials['Material.002']} position={[-1.076, -0.034, 0.146]} />
      <mesh name="Text001_cell078" geometry={nodes.Text001_cell078.geometry} material={materials['Material.002']} position={[-0.254, -1.19, -0.043]} />
      <mesh name="Text001_cell079" geometry={nodes.Text001_cell079.geometry} material={materials['Material.002']} position={[-1.336, 0.271, 0.029]} />
      <mesh name="Text001_cell080" geometry={nodes.Text001_cell080.geometry} material={materials['Material.002']} position={[-0.625, -1.37, -0.005]} />
      <mesh name="Text001_cell081" geometry={nodes.Text001_cell081.geometry} material={materials['Material.002']} position={[-1.602, 0.876, -0.151]} />
      <mesh name="Text001_cell082" geometry={nodes.Text001_cell082.geometry} material={materials['Material.002']} position={[-0.417, 0.582, 0.141]} />
      <mesh name="Text001_cell083" geometry={nodes.Text001_cell083.geometry} material={materials['Material.002']} position={[-0.281, -0.907, -0.092]} />
      <mesh name="Text001_cell084" geometry={nodes.Text001_cell084.geometry} material={materials['Material.002']} position={[-1.093, 1.022, -0.116]} />
      <mesh name="Text001_cell085" geometry={nodes.Text001_cell085.geometry} material={materials['Material.002']} position={[-0.442, 1.274, 0.156]} />
      <mesh name="Text001_cell086" geometry={nodes.Text001_cell086.geometry} material={materials['Material.002']} position={[-0.307, -0.064, -0.095]} />
      <mesh name="Text001_cell087" geometry={nodes.Text001_cell087.geometry} material={materials['Material.002']} position={[-0.821, -0.327, -0.047]} />
      <mesh name="Text001_cell088" geometry={nodes.Text001_cell088.geometry} material={materials['Material.002']} position={[-1.877, 0.244, -0.141]} />
      <mesh name="Text001_cell089" geometry={nodes.Text001_cell089.geometry} material={materials['Material.002']} position={[-1.341, 0.089, -0.121]} />
      <mesh name="Text001_cell090" geometry={nodes.Text001_cell090.geometry} material={materials['Material.002']} position={[-1.494, -0.057, -0.137]} />
      <mesh name="Text001_cell091" geometry={nodes.Text001_cell091.geometry} material={materials['Material.002']} position={[-0.854, 0.858, 0]} />
      <mesh name="Text001_cell092" geometry={nodes.Text001_cell092.geometry} material={materials['Material.002']} position={[-0.653, -0.6, -0.09]} />
      <mesh name="Text001_cell093" geometry={nodes.Text001_cell093.geometry} material={materials['Material.002']} position={[-0.718, 0.139, 0.125]} />
      <mesh name="Text001_cell094" geometry={nodes.Text001_cell094.geometry} material={materials['Material.002']} position={[-0.365, -0.071, 0.109]} />
      <mesh name="Text001_cell095" geometry={nodes.Text001_cell095.geometry} material={materials['Material.002']} position={[-1.628, 0.678, -0.111]} />
      <mesh name="Text001_cell096" geometry={nodes.Text001_cell096.geometry} material={materials['Material.002']} position={[-0.733, 0.356, -0.107]} />
      <mesh name="Text001_cell097" geometry={nodes.Text001_cell097.geometry} material={materials['Material.002']} position={[-1.972, 0.399, 0.14]} />
      <mesh name="Text001_cell098" geometry={nodes.Text001_cell098.geometry} material={materials['Material.002']} position={[-1.596, -0.043, 0.118]} />
      <mesh name="Text001_cell099" geometry={nodes.Text001_cell099.geometry} material={materials['Material.002']} position={[-0.804, -0.07, -0.131]} />
    </group>
  )
}

useGLTF.preload('/logoPP5.glb')
